# -*- coding: utf-8 -*-
"""SQL EDA FOR FINANCIALS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMxaUdnJRONvXAk3bEV7_Ir1DylfOgvr
"""

# ============================================================
# FINANCIALS EDA — SENIOR-LEVEL SQL ANALYSIS
# Tool: DuckDB (in-process SQL engine, reads CSV directly)
# ============================================================

!pip install duckdb --quiet

import duckdb
import pandas as pd
import os
import shutil
from google.colab import files

os.makedirs("sql_output", exist_ok=True)
con = duckdb.connect()

# ------------------------------------------------------------
# 0. LOAD AND CLEAN IN SQL
# ------------------------------------------------------------
con.execute("""
CREATE OR REPLACE TABLE financials AS
SELECT
    TRIM(Segment)                             AS segment,
    TRIM(Country)                             AS country,
    TRIM(Product)                             AS product,
    TRIM("Discount Band")                     AS discount_band,
    CAST(REPLACE(REPLACE(TRIM("Units Sold"), ',', ''), '$', '') AS DOUBLE) AS units_sold,
    CAST(REPLACE(REPLACE(TRIM("Manufacturing Price"), ',', ''), '$', '') AS DOUBLE) AS mfg_price,
    CAST(REPLACE(REPLACE(TRIM("Sale Price"), ',', ''), '$', '') AS DOUBLE) AS sale_price,
    CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE) AS gross_sales,
    CAST(REPLACE(REPLACE(TRIM(Discounts), ',', ''), '$', '') AS DOUBLE) AS discounts,
    CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE) AS sales,
    CAST(REPLACE(REPLACE(TRIM(COGS), ',', ''), '$', '') AS DOUBLE) AS cogs,
    CAST(REPLACE(REPLACE(TRIM(Profit), ',', ''), '$', '') AS DOUBLE) AS profit,
    TRY_CAST(TRIM(Date) AS DATE)              AS sale_date,
    CAST(TRIM("Month Number") AS INTEGER)     AS month_num,
    TRIM("Month Name")                        AS month_name,
    CAST(TRIM(Year) AS INTEGER)               AS year,
    CASE WHEN CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE) = 0
         THEN NULL
         ELSE CAST(REPLACE(REPLACE(TRIM(Profit), ',', ''), '$', '') AS DOUBLE)
              / CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE)
    END                                        AS margin,
    CASE WHEN CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE) = 0
         THEN NULL
         ELSE CAST(REPLACE(REPLACE(TRIM(Discounts), ',', ''), '$', '') AS DOUBLE)
              / CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE)
    END                                        AS discount_pct
FROM read_csv_auto('Financials.csv', header=true)
WHERE TRIM(Country) IS NOT NULL
  AND TRIM(Sales) IS NOT NULL;
""")

print("Table loaded.")
print(con.execute("SELECT COUNT(*) AS rows FROM financials").fetchdf())
print(con.execute("SELECT SUM(sales) AS total_sales, SUM(profit) AS total_profit FROM financials").fetchdf())


# ------------------------------------------------------------
# 1. BASELINE — CORE KPIs
# ------------------------------------------------------------
q01 = con.execute("""
SELECT
    COUNT(*)                          AS orders,
    COUNT(DISTINCT country)           AS countries,
    COUNT(DISTINCT product)           AS products,
    COUNT(DISTINCT segment)           AS segments,
    COUNT(DISTINCT discount_band)     AS discount_bands,
    ROUND(SUM(sales), 2)              AS total_sales,
    ROUND(SUM(cogs), 2)               AS total_cogs,
    ROUND(SUM(profit), 2)             AS total_profit,
    ROUND(SUM(units_sold), 2)         AS total_units,
    ROUND(SUM(profit) / SUM(sales), 4)        AS profit_margin,
    ROUND(SUM(cogs) / SUM(sales), 4)          AS cogs_to_sales,
    ROUND(SUM(profit) / SUM(units_sold), 2)   AS profit_per_unit
FROM financials;
""").fetchdf()
print("\n--- Q01: Core KPIs ---")
print(q01)
q01.to_csv("sql_output/q01_core_kpis.csv", index=False)


# ------------------------------------------------------------
# 2. COUNTRY PERFORMANCE
# ------------------------------------------------------------
q02 = con.execute("""
SELECT
    country,
    ROUND(SUM(sales), 2)      AS total_sales,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(units_sold), 2) AS total_units,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    ROUND(SUM(profit) / SUM(units_sold), 2) AS profit_per_unit
FROM financials
GROUP BY country
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q02: Country Performance ---")
print(q02)
q02.to_csv("sql_output/q02_country_performance.csv", index=False)


# ------------------------------------------------------------
# 3. PRODUCT PERFORMANCE
# ------------------------------------------------------------
q03 = con.execute("""
SELECT
    product,
    ROUND(SUM(sales), 2)      AS total_sales,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    ROUND(100.0 * SUM(profit) / (SELECT SUM(profit) FROM financials), 2) AS pct_of_total_profit
FROM financials
GROUP BY product
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q03: Product Performance (with % of total profit) ---")
print(q03)
q03.to_csv("sql_output/q03_product_performance.csv", index=False)


# ------------------------------------------------------------
# 4. DISCOUNT BAND — UNIT ECONOMICS
# ------------------------------------------------------------
q04 = con.execute("""
SELECT
    discount_band,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(units_sold), 2) AS total_units,
    ROUND(SUM(profit) / SUM(units_sold), 2) AS profit_per_unit,
    ROUND(AVG(discount_pct), 4)              AS avg_discount_pct,
    ROUND(100.0 * SUM(profit) / (SELECT SUM(profit) FROM financials), 2) AS pct_of_total_profit
FROM financials
GROUP BY discount_band
ORDER BY profit_per_unit DESC;
""").fetchdf()
print("\n--- Q04: Discount Band Unit Economics ---")
print(q04)
q04.to_csv("sql_output/q04_discount_band_economics.csv", index=False)


# ------------------------------------------------------------
# 5. CROSS-TAB: COUNTRY × DISCOUNT BAND
# ------------------------------------------------------------
q05 = con.execute("""
SELECT
    country,
    ROUND(SUM(CASE WHEN discount_band = 'None'   THEN profit ELSE 0 END), 2) AS none_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Low'    THEN profit ELSE 0 END), 2) AS low_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Medium' THEN profit ELSE 0 END), 2) AS medium_profit,
    ROUND(SUM(CASE WHEN discount_band = 'High'   THEN profit ELSE 0 END), 2) AS high_profit,
    ROUND(SUM(profit), 2) AS total_profit
FROM financials
GROUP BY country
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q05: Country × Discount Band (Profit) ---")
print(q05)
q05.to_csv("sql_output/q05_country_x_discount.csv", index=False)


# ------------------------------------------------------------
# 6. CROSS-TAB: PRODUCT × DISCOUNT BAND
# ------------------------------------------------------------
q06 = con.execute("""
SELECT
    product,
    ROUND(SUM(CASE WHEN discount_band = 'None'   THEN profit ELSE 0 END), 2) AS none_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Low'    THEN profit ELSE 0 END), 2) AS low_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Medium' THEN profit ELSE 0 END), 2) AS medium_profit,
    ROUND(SUM(CASE WHEN discount_band = 'High'   THEN profit ELSE 0 END), 2) AS high_profit,
    ROUND(SUM(profit), 2) AS total_profit
FROM financials
GROUP BY product
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q06: Product × Discount Band (Profit) ---")
print(q06)
q06.to_csv("sql_output/q06_product_x_discount.csv", index=False)


# ------------------------------------------------------------
# 7. MONTHLY TREND
# ------------------------------------------------------------
q07 = con.execute("""
SELECT
    month_num,
    month_name,
    COUNT(*)                  AS orders,
    ROUND(SUM(sales), 2)      AS sales,
    ROUND(SUM(profit), 2)     AS profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin
FROM financials
GROUP BY month_num, month_name
ORDER BY month_num;
""").fetchdf()
print("\n--- Q07: Monthly Trend ---")
print(q07)
q07.to_csv("sql_output/q07_monthly_trend.csv", index=False)


# ------------------------------------------------------------
# 8. WINDOW FUNCTION — Running YTD Profit by Month
# ------------------------------------------------------------
q08 = con.execute("""
WITH monthly AS (
    SELECT month_num, month_name,
           SUM(profit) AS month_profit
    FROM financials
    GROUP BY month_num, month_name
)
SELECT
    month_num,
    month_name,
    ROUND(month_profit, 2) AS month_profit,
    ROUND(SUM(month_profit) OVER (ORDER BY month_num), 2) AS ytd_profit
FROM monthly
ORDER BY month_num;
""").fetchdf()
print("\n--- Q08: YTD Profit Running Total ---")
print(q08)
q08.to_csv("sql_output/q08_ytd_profit.csv", index=False)


# ------------------------------------------------------------
# 9. WINDOW FUNCTION — Rank Countries Within Each Discount Band
# ------------------------------------------------------------
q09 = con.execute("""
WITH country_band AS (
    SELECT country, discount_band, SUM(profit) AS profit
    FROM financials
    GROUP BY country, discount_band
)
SELECT
    discount_band,
    country,
    ROUND(profit, 2) AS profit,
    RANK() OVER (PARTITION BY discount_band ORDER BY profit DESC) AS rank_in_band
FROM country_band
ORDER BY discount_band, rank_in_band;
""").fetchdf()
print("\n--- Q09: Country Rank Within Each Discount Band ---")
print(q09)
q09.to_csv("sql_output/q09_country_rank_by_band.csv", index=False)


# ------------------------------------------------------------
# 10. CTE — Countries Below Blended Margin
# ------------------------------------------------------------
q10 = con.execute("""
WITH country_margin AS (
    SELECT country,
           SUM(profit) AS profit,
           SUM(sales)  AS sales,
           SUM(profit) / SUM(sales) AS margin
    FROM financials
    GROUP BY country
),
blended AS (
    SELECT SUM(profit) / SUM(sales) AS blended_margin FROM financials
)
SELECT
    c.country,
    ROUND(c.margin, 4) AS margin,
    ROUND(b.blended_margin, 4) AS blended_margin,
    ROUND(c.margin - b.blended_margin, 4) AS gap,
    CASE WHEN c.margin < b.blended_margin THEN 'Below' ELSE 'Above' END AS position
FROM country_margin c, blended b
ORDER BY c.margin DESC;
""").fetchdf()
print("\n--- Q10: Countries vs Blended Margin ---")
print(q10)
q10.to_csv("sql_output/q10_vs_blended_margin.csv", index=False)


# ------------------------------------------------------------
# 11. CASE — Bucket Products by Margin Tier
# ------------------------------------------------------------
q11 = con.execute("""
WITH product_margin AS (
    SELECT product,
           SUM(profit) AS profit,
           SUM(sales)  AS sales,
           SUM(profit) / SUM(sales) AS margin
    FROM financials
    GROUP BY product
)
SELECT
    product,
    ROUND(margin, 4) AS margin,
    CASE
        WHEN margin >= 0.15 THEN 'High Margin'
        WHEN margin >= 0.12 THEN 'Mid Margin'
        ELSE 'Low Margin'
    END AS margin_tier
FROM product_margin
ORDER BY margin DESC;
""").fetchdf()
print("\n--- Q11: Product Margin Tiers ---")
print(q11)
q11.to_csv("sql_output/q11_product_margin_tiers.csv", index=False)


# ------------------------------------------------------------
# 12. JOIN — Product Lookup + Sales Aggregation
# ------------------------------------------------------------
q12 = con.execute("""
WITH product_lookup AS (
    SELECT
        product,
        ROUND(AVG(mfg_price), 2) AS avg_mfg_price,
        ROUND(AVG(sale_price), 2) AS avg_sale_price
    FROM financials
    GROUP BY product
),
product_agg AS (
    SELECT product,
           SUM(units_sold) AS units,
           SUM(sales) AS sales,
           SUM(profit) AS profit
    FROM financials
    GROUP BY product
)
SELECT
    p.product,
    p.avg_mfg_price,
    p.avg_sale_price,
    ROUND(p.avg_sale_price - p.avg_mfg_price, 2) AS gross_spread,
    a.units,
    ROUND(a.sales, 2) AS sales,
    ROUND(a.profit, 2) AS profit,
    ROUND(a.profit / a.sales, 4) AS margin
FROM product_lookup p
JOIN product_agg a USING (product)
ORDER BY a.profit DESC;
""").fetchdf()
print("\n--- Q12: Product Lookup + Sales (JOIN) ---")
print(q12)
q12.to_csv("sql_output/q12_product_join.csv", index=False)


# ------------------------------------------------------------
# 13. SUBQUERY — Top 3 Products by Profit in Each Country
# ------------------------------------------------------------
q13 = con.execute("""
WITH country_product AS (
    SELECT country, product, SUM(profit) AS profit
    FROM financials
    GROUP BY country, product
),
ranked AS (
    SELECT
        country, product, profit,
        ROW_NUMBER() OVER (PARTITION BY country ORDER BY profit DESC) AS rn
    FROM country_product
)
SELECT country, product, ROUND(profit, 2) AS profit
FROM ranked
WHERE rn <= 3
ORDER BY country, profit DESC;
""").fetchdf()
print("\n--- Q13: Top 3 Products by Profit per Country ---")
print(q13)
q13.to_csv("sql_output/q13_top_products_by_country.csv", index=False)


# ------------------------------------------------------------
# 14. CTE + WINDOW — Discount Band Share of Profit per Country
# ------------------------------------------------------------
q14 = con.execute("""
WITH cb AS (
    SELECT country, discount_band, SUM(profit) AS profit
    FROM financials
    GROUP BY country, discount_band
)
SELECT
    country,
    discount_band,
    ROUND(profit, 2) AS profit,
    ROUND(100.0 * profit / SUM(profit) OVER (PARTITION BY country), 2) AS pct_of_country_profit
FROM cb
ORDER BY country, pct_of_country_profit DESC;
""").fetchdf()
print("\n--- Q14: Discount Band Share of Country Profit ---")
print(q14)
q14.to_csv("sql_output/q14_band_share_by_country.csv", index=False)


# ------------------------------------------------------------
# 15. FINAL — Summary View
# ------------------------------------------------------------
q15 = con.execute("""
SELECT
    country,
    product,
    discount_band,
    ROUND(SUM(sales), 2)  AS sales,
    ROUND(SUM(profit), 2) AS profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    CASE
        WHEN SUM(profit) < 0 THEN 'Loss-making'
        WHEN SUM(profit) / SUM(sales) >= 0.15 THEN 'High margin'
        WHEN SUM(profit) / SUM(sales) >= 0.12 THEN 'Mid margin'
        ELSE 'Low margin'
    END AS tier
FROM financials
GROUP BY country, product, discount_band
ORDER BY profit DESC
LIMIT 30;
""").fetchdf()
print("\n--- Q15: Top 30 Country × Product × Discount Combinations ---")
print(q15)
q15.to_csv("sql_output/q15_top_combinations.csv", index=False)


# ------------------------------------------------------------
# ZIP AND DOWNLOAD
# ------------------------------------------------------------
shutil.make_archive("sql_output", "zip", "sql_output")
files.download("sql_output.zip")

print("\n" + "=" * 60)
print("SQL ANALYSIS COMPLETE")
print("=" * 60)
print("Downloaded: sql_output.zip")
print("Contents:")
for f in sorted(os.listdir("sql_output")):
    print("  -", f)

# ============================================================
# FINANCIALS EDA — SENIOR-LEVEL SQL ANALYSIS
# Tool: DuckDB (in-process SQL engine, reads CSV directly)
# ============================================================

!pip install duckdb --quiet

import duckdb
import pandas as pd
import os
import shutil
from google.colab import files

os.makedirs("sql_output", exist_ok=True)
con = duckdb.connect()

# ------------------------------------------------------------
# 0. LOAD AND CLEAN IN SQL
# ------------------------------------------------------------
con.execute("""
CREATE OR REPLACE TABLE financials AS
SELECT
    TRIM(Segment)                             AS segment,
    TRIM(Country)                             AS country,
    TRIM(Product)                             AS product,
    TRIM("Discount Band")                     AS discount_band,
    CAST(REPLACE(REPLACE(TRIM("Units Sold"), ',', ''), '$', '') AS DOUBLE) AS units_sold,
    CAST(REPLACE(REPLACE(TRIM("Manufacturing Price"), ',', ''), '$', '') AS DOUBLE) AS mfg_price,
    CAST(REPLACE(REPLACE(TRIM("Sale Price"), ',', ''), '$', '') AS DOUBLE) AS sale_price,
    CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE) AS gross_sales,
    CAST(REPLACE(REPLACE(TRIM(Discounts), ',', ''), '$', '') AS DOUBLE) AS discounts,
    CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE) AS sales,
    CAST(REPLACE(REPLACE(TRIM(COGS), ',', ''), '$', '') AS DOUBLE) AS cogs,
    CAST(REPLACE(REPLACE(TRIM(Profit), ',', ''), '$', '') AS DOUBLE) AS profit,
    TRY_CAST(TRIM(Date) AS DATE)              AS sale_date,
    CAST(TRIM("Month Number") AS INTEGER)     AS month_num,
    TRIM("Month Name")                        AS month_name,
    CAST(TRIM(Year) AS INTEGER)               AS year,
    CASE WHEN CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE) = 0
         THEN NULL
         ELSE CAST(REPLACE(REPLACE(TRIM(Profit), ',', ''), '$', '') AS DOUBLE)
              / CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE)
    END                                        AS margin,
    CASE WHEN CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE) = 0
         THEN NULL
         ELSE CAST(REPLACE(REPLACE(TRIM(Discounts), ',', ''), '$', '') AS DOUBLE)
              / CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE)
    END                                        AS discount_pct
FROM read_csv_auto('Financials.csv', header=true)
WHERE TRIM(Country) IS NOT NULL
  AND TRIM(Sales) IS NOT NULL;
""")

print("Table loaded.")
print(con.execute("SELECT COUNT(*) AS rows FROM financials").fetchdf())
print(con.execute("SELECT SUM(sales) AS total_sales, SUM(profit) AS total_profit FROM financials").fetchdf())


# ------------------------------------------------------------
# 1. BASELINE — CORE KPIs
# ------------------------------------------------------------
q01 = con.execute("""
SELECT
    COUNT(*)                          AS orders,
    COUNT(DISTINCT country)           AS countries,
    COUNT(DISTINCT product)           AS products,
    COUNT(DISTINCT segment)           AS segments,
    COUNT(DISTINCT discount_band)     AS discount_bands,
    ROUND(SUM(sales), 2)              AS total_sales,
    ROUND(SUM(cogs), 2)               AS total_cogs,
    ROUND(SUM(profit), 2)             AS total_profit,
    ROUND(SUM(units_sold), 2)         AS total_units,
    ROUND(SUM(profit) / SUM(sales), 4)        AS profit_margin,
    ROUND(SUM(cogs) / SUM(sales), 4)          AS cogs_to_sales,
    ROUND(SUM(profit) / SUM(units_sold), 2)   AS profit_per_unit
FROM financials;
""").fetchdf()
print("\n--- Q01: Core KPIs ---")
print(q01)
q01.to_csv("sql_output/q01_core_kpis.csv", index=False)


# ------------------------------------------------------------
# 2. COUNTRY PERFORMANCE
# ------------------------------------------------------------
q02 = con.execute("""
SELECT
    country,
    ROUND(SUM(sales), 2)      AS total_sales,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(units_sold), 2) AS total_units,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    ROUND(SUM(profit) / SUM(units_sold), 2) AS profit_per_unit
FROM financials
GROUP BY country
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q02: Country Performance ---")
print(q02)
q02.to_csv("sql_output/q02_country_performance.csv", index=False)


# ------------------------------------------------------------
# 3. PRODUCT PERFORMANCE
# ------------------------------------------------------------
q03 = con.execute("""
SELECT
    product,
    ROUND(SUM(sales), 2)      AS total_sales,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    ROUND(100.0 * SUM(profit) / (SELECT SUM(profit) FROM financials), 2) AS pct_of_total_profit
FROM financials
GROUP BY product
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q03: Product Performance (with % of total profit) ---")
print(q03)
q03.to_csv("sql_output/q03_product_performance.csv", index=False)


# ------------------------------------------------------------
# 4. DISCOUNT BAND — UNIT ECONOMICS
# ------------------------------------------------------------
q04 = con.execute("""
SELECT
    discount_band,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(units_sold), 2) AS total_units,
    ROUND(SUM(profit) / SUM(units_sold), 2) AS profit_per_unit,
    ROUND(AVG(discount_pct), 4)              AS avg_discount_pct,
    ROUND(100.0 * SUM(profit) / (SELECT SUM(profit) FROM financials), 2) AS pct_of_total_profit
FROM financials
GROUP BY discount_band
ORDER BY profit_per_unit DESC;
""").fetchdf()
print("\n--- Q04: Discount Band Unit Economics ---")
print(q04)
q04.to_csv("sql_output/q04_discount_band_economics.csv", index=False)


# ------------------------------------------------------------
# 5. CROSS-TAB: COUNTRY × DISCOUNT BAND
# ------------------------------------------------------------
q05 = con.execute("""
SELECT
    country,
    ROUND(SUM(CASE WHEN discount_band = 'None'   THEN profit ELSE 0 END), 2) AS none_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Low'    THEN profit ELSE 0 END), 2) AS low_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Medium' THEN profit ELSE 0 END), 2) AS medium_profit,
    ROUND(SUM(CASE WHEN discount_band = 'High'   THEN profit ELSE 0 END), 2) AS high_profit,
    ROUND(SUM(profit), 2) AS total_profit
FROM financials
GROUP BY country
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q05: Country × Discount Band (Profit) ---")
print(q05)
q05.to_csv("sql_output/q05_country_x_discount.csv", index=False)


# ------------------------------------------------------------
# 6. CROSS-TAB: PRODUCT × DISCOUNT BAND
# ------------------------------------------------------------
q06 = con.execute("""
SELECT
    product,
    ROUND(SUM(CASE WHEN discount_band = 'None'   THEN profit ELSE 0 END), 2) AS none_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Low'    THEN profit ELSE 0 END), 2) AS low_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Medium' THEN profit ELSE 0 END), 2) AS medium_profit,
    ROUND(SUM(CASE WHEN discount_band = 'High'   THEN profit ELSE 0 END), 2) AS high_profit,
    ROUND(SUM(profit), 2) AS total_profit
FROM financials
GROUP BY product
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q06: Product × Discount Band (Profit) ---")
print(q06)
q06.to_csv("sql_output/q06_product_x_discount.csv", index=False)


# ------------------------------------------------------------
# 7. MONTHLY TREND
# ------------------------------------------------------------
q07 = con.execute("""
SELECT
    month_num,
    month_name,
    COUNT(*)                  AS orders,
    ROUND(SUM(sales), 2)      AS sales,
    ROUND(SUM(profit), 2)     AS profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin
FROM financials
GROUP BY month_num, month_name
ORDER BY month_num;
""").fetchdf()
print("\n--- Q07: Monthly Trend ---")
print(q07)
q07.to_csv("sql_output/q07_monthly_trend.csv", index=False)


# ------------------------------------------------------------
# 8. WINDOW FUNCTION — Running YTD Profit by Month
# ------------------------------------------------------------
q08 = con.execute("""
WITH monthly AS (
    SELECT month_num, month_name,
           SUM(profit) AS month_profit
    FROM financials
    GROUP BY month_num, month_name
)
SELECT
    month_num,
    month_name,
    ROUND(month_profit, 2) AS month_profit,
    ROUND(SUM(month_profit) OVER (ORDER BY month_num), 2) AS ytd_profit
FROM monthly
ORDER BY month_num;
""").fetchdf()
print("\n--- Q08: YTD Profit Running Total ---")
print(q08)
q08.to_csv("sql_output/q08_ytd_profit.csv", index=False)


# ------------------------------------------------------------
# 9. WINDOW FUNCTION — Rank Countries Within Each Discount Band
# ------------------------------------------------------------
q09 = con.execute("""
WITH country_band AS (
    SELECT country, discount_band, SUM(profit) AS profit
    FROM financials
    GROUP BY country, discount_band
)
SELECT
    discount_band,
    country,
    ROUND(profit, 2) AS profit,
    RANK() OVER (PARTITION BY discount_band ORDER BY profit DESC) AS rank_in_band
FROM country_band
ORDER BY discount_band, rank_in_band;
""").fetchdf()
print("\n--- Q09: Country Rank Within Each Discount Band ---")
print(q09)
q09.to_csv("sql_output/q09_country_rank_by_band.csv", index=False)


# ------------------------------------------------------------
# 10. CTE — Countries Below Blended Margin
# ------------------------------------------------------------
q10 = con.execute("""
WITH country_margin AS (
    SELECT country,
           SUM(profit) AS profit,
           SUM(sales)  AS sales,
           SUM(profit) / SUM(sales) AS margin
    FROM financials
    GROUP BY country
),
blended AS (
    SELECT SUM(profit) / SUM(sales) AS blended_margin FROM financials
)
SELECT
    c.country,
    ROUND(c.margin, 4) AS margin,
    ROUND(b.blended_margin, 4) AS blended_margin,
    ROUND(c.margin - b.blended_margin, 4) AS gap,
    CASE WHEN c.margin < b.blended_margin THEN 'Below' ELSE 'Above' END AS position
FROM country_margin c, blended b
ORDER BY c.margin DESC;
""").fetchdf()
print("\n--- Q10: Countries vs Blended Margin ---")
print(q10)
q10.to_csv("sql_output/q10_vs_blended_margin.csv", index=False)


# ------------------------------------------------------------
# 11. CASE — Bucket Products by Margin Tier
# ------------------------------------------------------------
q11 = con.execute("""
WITH product_margin AS (
    SELECT product,
           SUM(profit) AS profit,
           SUM(sales)  AS sales,
           SUM(profit) / SUM(sales) AS margin
    FROM financials
    GROUP BY product
)
SELECT
    product,
    ROUND(margin, 4) AS margin,
    CASE
        WHEN margin >= 0.15 THEN 'High Margin'
        WHEN margin >= 0.12 THEN 'Mid Margin'
        ELSE 'Low Margin'
    END AS margin_tier
FROM product_margin
ORDER BY margin DESC;
""").fetchdf()
print("\n--- Q11: Product Margin Tiers ---")
print(q11)
q11.to_csv("sql_output/q11_product_margin_tiers.csv", index=False)


# ------------------------------------------------------------
# 12. JOIN — Product Lookup + Sales Aggregation
# ------------------------------------------------------------
q12 = con.execute("""
WITH product_lookup AS (
    SELECT
        product,
        ROUND(AVG(mfg_price), 2) AS avg_mfg_price,
        ROUND(AVG(sale_price), 2) AS avg_sale_price
    FROM financials
    GROUP BY product
),
product_agg AS (
    SELECT product,
           SUM(units_sold) AS units,
           SUM(sales) AS sales,
           SUM(profit) AS profit
    FROM financials
    GROUP BY product
)
SELECT
    p.product,
    p.avg_mfg_price,
    p.avg_sale_price,
    ROUND(p.avg_sale_price - p.avg_mfg_price, 2) AS gross_spread,
    a.units,
    ROUND(a.sales, 2) AS sales,
    ROUND(a.profit, 2) AS profit,
    ROUND(a.profit / a.sales, 4) AS margin
FROM product_lookup p
JOIN product_agg a USING (product)
ORDER BY a.profit DESC;
""").fetchdf()
print("\n--- Q12: Product Lookup + Sales (JOIN) ---")
print(q12)
q12.to_csv("sql_output/q12_product_join.csv", index=False)


# ------------------------------------------------------------
# 13. SUBQUERY — Top 3 Products by Profit in Each Country
# ------------------------------------------------------------
q13 = con.execute("""
WITH country_product AS (
    SELECT country, product, SUM(profit) AS profit
    FROM financials
    GROUP BY country, product
),
ranked AS (
    SELECT
        country, product, profit,
        ROW_NUMBER() OVER (PARTITION BY country ORDER BY profit DESC) AS rn
    FROM country_product
)
SELECT country, product, ROUND(profit, 2) AS profit
FROM ranked
WHERE rn <= 3
ORDER BY country, profit DESC;
""").fetchdf()
print("\n--- Q13: Top 3 Products by Profit per Country ---")
print(q13)
q13.to_csv("sql_output/q13_top_products_by_country.csv", index=False)


# ------------------------------------------------------------
# 14. CTE + WINDOW — Discount Band Share of Profit per Country
# ------------------------------------------------------------
q14 = con.execute("""
WITH cb AS (
    SELECT country, discount_band, SUM(profit) AS profit
    FROM financials
    GROUP BY country, discount_band
)
SELECT
    country,
    discount_band,
    ROUND(profit, 2) AS profit,
    ROUND(100.0 * profit / SUM(profit) OVER (PARTITION BY country), 2) AS pct_of_country_profit
FROM cb
ORDER BY country, pct_of_country_profit DESC;
""").fetchdf()
print("\n--- Q14: Discount Band Share of Country Profit ---")
print(q14)
q14.to_csv("sql_output/q14_band_share_by_country.csv", index=False)


# ------------------------------------------------------------
# 15. FINAL — Summary View
# ------------------------------------------------------------
q15 = con.execute("""
SELECT
    country,
    product,
    discount_band,
    ROUND(SUM(sales), 2)  AS sales,
    ROUND(SUM(profit), 2) AS profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    CASE
        WHEN SUM(profit) < 0 THEN 'Loss-making'
        WHEN SUM(profit) / SUM(sales) >= 0.15 THEN 'High margin'
        WHEN SUM(profit) / SUM(sales) >= 0.12 THEN 'Mid margin'
        ELSE 'Low margin'
    END AS tier
FROM financials
GROUP BY country, product, discount_band
ORDER BY profit DESC
LIMIT 30;
""").fetchdf()
print("\n--- Q15: Top 30 Country × Product × Discount Combinations ---")
print(q15)
q15.to_csv("sql_output/q15_top_combinations.csv", index=False)


# ------------------------------------------------------------
# ZIP AND DOWNLOAD
# ------------------------------------------------------------
shutil.make_archive("sql_output", "zip", "sql_output")
files.download("sql_output.zip")

print("\n" + "=" * 60)
print("SQL ANALYSIS COMPLETE")
print("=" * 60)
print("Downloaded: sql_output.zip")
print("Contents:")
for f in sorted(os.listdir("sql_output")):
    print("  -", f)

# ============================================================
# FINANCIALS EDA — SENIOR-LEVEL SQL ANALYSIS
# Tool: DuckDB (in-process SQL engine, reads CSV directly)
# ============================================================

!pip install duckdb --quiet

import duckdb
import pandas as pd
import os
import shutil
from google.colab import files

os.makedirs("sql_output", exist_ok=True)
con = duckdb.connect()

# ------------------------------------------------------------
# 0. LOAD AND CLEAN IN SQL
# ------------------------------------------------------------
con.execute("""
CREATE OR REPLACE TABLE financials AS
SELECT
    TRIM(Segment)                             AS segment,
    TRIM(Country)                             AS country,
    TRIM(Product)                             AS product,
    TRIM("Discount Band")                     AS discount_band,
    CAST(REPLACE(REPLACE(TRIM("Units Sold"), ',', ''), '$', '') AS DOUBLE) AS units_sold,
    CAST(REPLACE(REPLACE(TRIM("Manufacturing Price"), ',', ''), '$', '') AS DOUBLE) AS mfg_price,
    CAST(REPLACE(REPLACE(TRIM("Sale Price"), ',', ''), '$', '') AS DOUBLE) AS sale_price,
    CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE) AS gross_sales,
    CAST(REPLACE(REPLACE(TRIM(Discounts), ',', ''), '$', '') AS DOUBLE) AS discounts,
    CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE) AS sales,
    CAST(REPLACE(REPLACE(TRIM(COGS), ',', ''), '$', '') AS DOUBLE) AS cogs,
    CAST(REPLACE(REPLACE(TRIM(Profit), ',', ''), '$', '') AS DOUBLE) AS profit,
    CAST("Date" AS DATE)                      AS sale_date,
    CAST(TRIM("Month Number") AS INTEGER)     AS month_num,
    TRIM("Month Name")                        AS month_name,
    CAST(TRIM(Year) AS INTEGER)               AS year,
    CASE WHEN CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE) = 0
         THEN NULL
         ELSE CAST(REPLACE(REPLACE(TRIM(Profit), ',', ''), '$', '') AS DOUBLE)
              / CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE)
    END                                        AS margin,
    CASE WHEN CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE) = 0
         THEN NULL
         ELSE CAST(REPLACE(REPLACE(TRIM(Discounts), ',', ''), '$', '') AS DOUBLE)
              / CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE)
    END                                        AS discount_pct
FROM read_csv_auto('Financials.csv', header=true)
WHERE TRIM(Country) IS NOT NULL
  AND TRIM(Sales) IS NOT NULL;
""")

print("Table loaded.")
print(con.execute("SELECT COUNT(*) AS rows FROM financials").fetchdf())
print(con.execute("SELECT SUM(sales) AS total_sales, SUM(profit) AS total_profit FROM financials").fetchdf())


# ------------------------------------------------------------
# 1. BASELINE — CORE KPIs
# ------------------------------------------------------------
q01 = con.execute("""
SELECT
    COUNT(*)                          AS orders,
    COUNT(DISTINCT country)           AS countries,
    COUNT(DISTINCT product)           AS products,
    COUNT(DISTINCT segment)           AS segments,
    COUNT(DISTINCT discount_band)     AS discount_bands,
    ROUND(SUM(sales), 2)              AS total_sales,
    ROUND(SUM(cogs), 2)               AS total_cogs,
    ROUND(SUM(profit), 2)             AS total_profit,
    ROUND(SUM(units_sold), 2)         AS total_units,
    ROUND(SUM(profit) / SUM(sales), 4)        AS profit_margin,
    ROUND(SUM(cogs) / SUM(sales), 4)          AS cogs_to_sales,
    ROUND(SUM(profit) / SUM(units_sold), 2)   AS profit_per_unit
FROM financials;
""").fetchdf()
print("\n--- Q01: Core KPIs ---")
print(q01)
q01.to_csv("sql_output/q01_core_kpis.csv", index=False)


# ------------------------------------------------------------
# 2. COUNTRY PERFORMANCE
# ------------------------------------------------------------
q02 = con.execute("""
SELECT
    country,
    ROUND(SUM(sales), 2)      AS total_sales,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(units_sold), 2) AS total_units,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    ROUND(SUM(profit) / SUM(units_sold), 2) AS profit_per_unit
FROM financials
GROUP BY country
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q02: Country Performance ---")
print(q02)
q02.to_csv("sql_output/q02_country_performance.csv", index=False)


# ------------------------------------------------------------
# 3. PRODUCT PERFORMANCE
# ------------------------------------------------------------
q03 = con.execute("""
SELECT
    product,
    ROUND(SUM(sales), 2)      AS total_sales,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    ROUND(100.0 * SUM(profit) / (SELECT SUM(profit) FROM financials), 2) AS pct_of_total_profit
FROM financials
GROUP BY product
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q03: Product Performance (with % of total profit) ---")
print(q03)
q03.to_csv("sql_output/q03_product_performance.csv", index=False)


# ------------------------------------------------------------
# 4. DISCOUNT BAND — UNIT ECONOMICS
# ------------------------------------------------------------
q04 = con.execute("""
SELECT
    discount_band,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(units_sold), 2) AS total_units,
    ROUND(SUM(profit) / SUM(units_sold), 2) AS profit_per_unit,
    ROUND(AVG(discount_pct), 4)              AS avg_discount_pct,
    ROUND(100.0 * SUM(profit) / (SELECT SUM(profit) FROM financials), 2) AS pct_of_total_profit
FROM financials
GROUP BY discount_band
ORDER BY profit_per_unit DESC;
""").fetchdf()
print("\n--- Q04: Discount Band Unit Economics ---")
print(q04)
q04.to_csv("sql_output/q04_discount_band_economics.csv", index=False)


# ------------------------------------------------------------
# 5. CROSS-TAB: COUNTRY × DISCOUNT BAND
# ------------------------------------------------------------
q05 = con.execute("""
SELECT
    country,
    ROUND(SUM(CASE WHEN discount_band = 'None'   THEN profit ELSE 0 END), 2) AS none_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Low'    THEN profit ELSE 0 END), 2) AS low_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Medium' THEN profit ELSE 0 END), 2) AS medium_profit,
    ROUND(SUM(CASE WHEN discount_band = 'High'   THEN profit ELSE 0 END), 2) AS high_profit,
    ROUND(SUM(profit), 2) AS total_profit
FROM financials
GROUP BY country
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q05: Country × Discount Band (Profit) ---")
print(q05)
q05.to_csv("sql_output/q05_country_x_discount.csv", index=False)


# ------------------------------------------------------------
# 6. CROSS-TAB: PRODUCT × DISCOUNT BAND
# ------------------------------------------------------------
q06 = con.execute("""
SELECT
    product,
    ROUND(SUM(CASE WHEN discount_band = 'None'   THEN profit ELSE 0 END), 2) AS none_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Low'    THEN profit ELSE 0 END), 2) AS low_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Medium' THEN profit ELSE 0 END), 2) AS medium_profit,
    ROUND(SUM(CASE WHEN discount_band = 'High'   THEN profit ELSE 0 END), 2) AS high_profit,
    ROUND(SUM(profit), 2) AS total_profit
FROM financials
GROUP BY product
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q06: Product × Discount Band (Profit) ---")
print(q06)
q06.to_csv("sql_output/q06_product_x_discount.csv", index=False)


# ------------------------------------------------------------
# 7. MONTHLY TREND
# ------------------------------------------------------------
q07 = con.execute("""
SELECT
    month_num,
    month_name,
    COUNT(*)                  AS orders,
    ROUND(SUM(sales), 2)      AS sales,
    ROUND(SUM(profit), 2)     AS profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin
FROM financials
GROUP BY month_num, month_name
ORDER BY month_num;
""").fetchdf()
print("\n--- Q07: Monthly Trend ---")
print(q07)
q07.to_csv("sql_output/q07_monthly_trend.csv", index=False)


# ------------------------------------------------------------
# 8. WINDOW FUNCTION — Running YTD Profit by Month
# ------------------------------------------------------------
q08 = con.execute("""
WITH monthly AS (
    SELECT month_num, month_name,
           SUM(profit) AS month_profit
    FROM financials
    GROUP BY month_num, month_name
)
SELECT
    month_num,
    month_name,
    ROUND(month_profit, 2) AS month_profit,
    ROUND(SUM(month_profit) OVER (ORDER BY month_num), 2) AS ytd_profit
FROM monthly
ORDER BY month_num;
""").fetchdf()
print("\n--- Q08: YTD Profit Running Total ---")
print(q08)
q08.to_csv("sql_output/q08_ytd_profit.csv", index=False)


# ------------------------------------------------------------
# 9. WINDOW FUNCTION — Rank Countries Within Each Discount Band
# ------------------------------------------------------------
q09 = con.execute("""
WITH country_band AS (
    SELECT country, discount_band, SUM(profit) AS profit
    FROM financials
    GROUP BY country, discount_band
)
SELECT
    discount_band,
    country,
    ROUND(profit, 2) AS profit,
    RANK() OVER (PARTITION BY discount_band ORDER BY profit DESC) AS rank_in_band
FROM country_band
ORDER BY discount_band, rank_in_band;
""").fetchdf()
print("\n--- Q09: Country Rank Within Each Discount Band ---")
print(q09)
q09.to_csv("sql_output/q09_country_rank_by_band.csv", index=False)


# ------------------------------------------------------------
# 10. CTE — Countries Below Blended Margin
# ------------------------------------------------------------
q10 = con.execute("""
WITH country_margin AS (
    SELECT country,
           SUM(profit) AS profit,
           SUM(sales)  AS sales,
           SUM(profit) / SUM(sales) AS margin
    FROM financials
    GROUP BY country
),
blended AS (
    SELECT SUM(profit) / SUM(sales) AS blended_margin FROM financials
)
SELECT
    c.country,
    ROUND(c.margin, 4) AS margin,
    ROUND(b.blended_margin, 4) AS blended_margin,
    ROUND(c.margin - b.blended_margin, 4) AS gap,
    CASE WHEN c.margin < b.blended_margin THEN 'Below' ELSE 'Above' END AS position
FROM country_margin c, blended b
ORDER BY c.margin DESC;
""").fetchdf()
print("\n--- Q10: Countries vs Blended Margin ---")
print(q10)
q10.to_csv("sql_output/q10_vs_blended_margin.csv", index=False)


# ------------------------------------------------------------
# 11. CASE — Bucket Products by Margin Tier
# ------------------------------------------------------------
q11 = con.execute("""
WITH product_margin AS (
    SELECT product,
           SUM(profit) AS profit,
           SUM(sales)  AS sales,
           SUM(profit) / SUM(sales) AS margin
    FROM financials
    GROUP BY product
)
SELECT
    product,
    ROUND(margin, 4) AS margin,
    CASE
        WHEN margin >= 0.15 THEN 'High Margin'
        WHEN margin >= 0.12 THEN 'Mid Margin'
        ELSE 'Low Margin'
    END AS margin_tier
FROM product_margin
ORDER BY margin DESC;
""").fetchdf()
print("\n--- Q11: Product Margin Tiers ---")
print(q11)
q11.to_csv("sql_output/q11_product_margin_tiers.csv", index=False)


# ------------------------------------------------------------
# 12. JOIN — Product Lookup + Sales Aggregation
# ------------------------------------------------------------
q12 = con.execute("""
WITH product_lookup AS (
    SELECT
        product,
        ROUND(AVG(mfg_price), 2) AS avg_mfg_price,
        ROUND(AVG(sale_price), 2) AS avg_sale_price
    FROM financials
    GROUP BY product
),
product_agg AS (
    SELECT product,
           SUM(units_sold) AS units,
           SUM(sales) AS sales,
           SUM(profit) AS profit
    FROM financials
    GROUP BY product
)
SELECT
    p.product,
    p.avg_mfg_price,
    p.avg_sale_price,
    ROUND(p.avg_sale_price - p.avg_mfg_price, 2) AS gross_spread,
    a.units,
    ROUND(a.sales, 2) AS sales,
    ROUND(a.profit, 2) AS profit,
    ROUND(a.profit / a.sales, 4) AS margin
FROM product_lookup p
JOIN product_agg a USING (product)
ORDER BY a.profit DESC;
""").fetchdf()
print("\n--- Q12: Product Lookup + Sales (JOIN) ---")
print(q12)
q12.to_csv("sql_output/q12_product_join.csv", index=False)


# ------------------------------------------------------------
# 13. SUBQUERY — Top 3 Products by Profit in Each Country
# ------------------------------------------------------------
q13 = con.execute("""
WITH country_product AS (
    SELECT country, product, SUM(profit) AS profit
    FROM financials
    GROUP BY country, product
),
ranked AS (
    SELECT
        country, product, profit,
        ROW_NUMBER() OVER (PARTITION BY country ORDER BY profit DESC) AS rn
    FROM country_product
)
SELECT country, product, ROUND(profit, 2) AS profit
FROM ranked
WHERE rn <= 3
ORDER BY country, profit DESC;
""").fetchdf()
print("\n--- Q13: Top 3 Products by Profit per Country ---")
print(q13)
q13.to_csv("sql_output/q13_top_products_by_country.csv", index=False)


# ------------------------------------------------------------
# 14. CTE + WINDOW — Discount Band Share of Profit per Country
# ------------------------------------------------------------
q14 = con.execute("""
WITH cb AS (
    SELECT country, discount_band, SUM(profit) AS profit
    FROM financials
    GROUP BY country, discount_band
)
SELECT
    country,
    discount_band,
    ROUND(profit, 2) AS profit,
    ROUND(100.0 * profit / SUM(profit) OVER (PARTITION BY country), 2) AS pct_of_country_profit
FROM cb
ORDER BY country, pct_of_country_profit DESC;
""").fetchdf()
print("\n--- Q14: Discount Band Share of Country Profit ---")
print(q14)
q14.to_csv("sql_output/q14_band_share_by_country.csv", index=False)


# ------------------------------------------------------------
# 15. FINAL — Summary View
# ------------------------------------------------------------
q15 = con.execute("""
SELECT
    country,
    product,
    discount_band,
    ROUND(SUM(sales), 2)  AS sales,
    ROUND(SUM(profit), 2) AS profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    CASE
        WHEN SUM(profit) < 0 THEN 'Loss-making'
        WHEN SUM(profit) / SUM(sales) >= 0.15 THEN 'High margin'
        WHEN SUM(profit) / SUM(sales) >= 0.12 THEN 'Mid margin'
        ELSE 'Low margin'
    END AS tier
FROM financials
GROUP BY country, product, discount_band
ORDER BY profit DESC
LIMIT 30;
""").fetchdf()
print("\n--- Q15: Top 30 Country × Product × Discount Combinations ---")
print(q15)
q15.to_csv("sql_output/q15_top_combinations.csv", index=False)


# ------------------------------------------------------------
# ZIP AND DOWNLOAD
# ------------------------------------------------------------
shutil.make_archive("sql_output", "zip", "sql_output")
files.download("sql_output.zip")

print("\n" + "=" * 60)
print("SQL ANALYSIS COMPLETE")
print("=" * 60)
print("Downloaded: sql_output.zip")
print("Contents:")
for f in sorted(os.listdir("sql_output")):
    print("  -", f)

# ============================================================
# FINANCIALS EDA — SENIOR-LEVEL SQL ANALYSIS
# Tool: DuckDB (in-process SQL engine, reads CSV directly)
# ============================================================

!pip install duckdb --quiet

import duckdb
import pandas as pd
import os
import shutil
from google.colab import files

os.makedirs("sql_output", exist_ok=True)
con = duckdb.connect()

# ------------------------------------------------------------
# 0. LOAD AND CLEAN IN SQL
# ------------------------------------------------------------
con.execute("""
CREATE OR REPLACE TABLE financials AS
SELECT
    TRIM(Segment)                             AS segment,
    TRIM(Country)                             AS country,
    TRIM(Product)                             AS product,
    TRIM("Discount Band")                     AS discount_band,
    CAST(REPLACE(REPLACE(TRIM("Units Sold"), ',', ''), '$', '') AS DOUBLE) AS units_sold,
    CAST(REPLACE(REPLACE(TRIM("Manufacturing Price"), ',', ''), '$', '') AS DOUBLE) AS mfg_price,
    CAST(REPLACE(REPLACE(TRIM("Sale Price"), ',', ''), '$', '') AS DOUBLE) AS sale_price,
    CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE) AS gross_sales,
    CAST(REPLACE(REPLACE(TRIM(Discounts), ',', ''), '$', '') AS DOUBLE) AS discounts,
    CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE) AS sales,
    CAST(REPLACE(REPLACE(TRIM(COGS), ',', ''), '$', '') AS DOUBLE) AS cogs,
    CAST(REPLACE(REPLACE(TRIM(Profit), ',', ''), '$', '') AS DOUBLE) AS profit,
    CAST("Date" AS DATE)                      AS sale_date,
    CAST("Month Number" AS INTEGER)           AS month_num,
    TRIM("Month Name")                        AS month_name,
    CAST("Year" AS INTEGER)                   AS year,
    CASE WHEN CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE) = 0
         THEN NULL
         ELSE CAST(REPLACE(REPLACE(TRIM(Profit), ',', ''), '$', '') AS DOUBLE)
              / CAST(REPLACE(REPLACE(TRIM(Sales), ',', ''), '$', '') AS DOUBLE)
    END                                        AS margin,
    CASE WHEN CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE) = 0
         THEN NULL
         ELSE CAST(REPLACE(REPLACE(TRIM(Discounts), ',', ''), '$', '') AS DOUBLE)
              / CAST(REPLACE(REPLACE(TRIM("Gross Sales"), ',', ''), '$', '') AS DOUBLE)
    END                                        AS discount_pct
FROM read_csv_auto('Financials.csv', header=true)
WHERE TRIM(Country) IS NOT NULL
  AND TRIM(Sales) IS NOT NULL;
""")

print("Table loaded.")
print(con.execute("SELECT COUNT(*) AS rows FROM financials").fetchdf())
print(con.execute("SELECT SUM(sales) AS total_sales, SUM(profit) AS total_profit FROM financials").fetchdf())


# ------------------------------------------------------------
# 1. BASELINE — CORE KPIs
# ------------------------------------------------------------
q01 = con.execute("""
SELECT
    COUNT(*)                          AS orders,
    COUNT(DISTINCT country)           AS countries,
    COUNT(DISTINCT product)           AS products,
    COUNT(DISTINCT segment)           AS segments,
    COUNT(DISTINCT discount_band)     AS discount_bands,
    ROUND(SUM(sales), 2)              AS total_sales,
    ROUND(SUM(cogs), 2)               AS total_cogs,
    ROUND(SUM(profit), 2)             AS total_profit,
    ROUND(SUM(units_sold), 2)         AS total_units,
    ROUND(SUM(profit) / SUM(sales), 4)        AS profit_margin,
    ROUND(SUM(cogs) / SUM(sales), 4)          AS cogs_to_sales,
    ROUND(SUM(profit) / SUM(units_sold), 2)   AS profit_per_unit
FROM financials;
""").fetchdf()
print("\n--- Q01: Core KPIs ---")
print(q01)
q01.to_csv("sql_output/q01_core_kpis.csv", index=False)


# ------------------------------------------------------------
# 2. COUNTRY PERFORMANCE
# ------------------------------------------------------------
q02 = con.execute("""
SELECT
    country,
    ROUND(SUM(sales), 2)      AS total_sales,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(units_sold), 2) AS total_units,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    ROUND(SUM(profit) / SUM(units_sold), 2) AS profit_per_unit
FROM financials
GROUP BY country
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q02: Country Performance ---")
print(q02)
q02.to_csv("sql_output/q02_country_performance.csv", index=False)


# ------------------------------------------------------------
# 3. PRODUCT PERFORMANCE
# ------------------------------------------------------------
q03 = con.execute("""
SELECT
    product,
    ROUND(SUM(sales), 2)      AS total_sales,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    ROUND(100.0 * SUM(profit) / (SELECT SUM(profit) FROM financials), 2) AS pct_of_total_profit
FROM financials
GROUP BY product
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q03: Product Performance (with % of total profit) ---")
print(q03)
q03.to_csv("sql_output/q03_product_performance.csv", index=False)


# ------------------------------------------------------------
# 4. DISCOUNT BAND — UNIT ECONOMICS
# ------------------------------------------------------------
q04 = con.execute("""
SELECT
    discount_band,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(units_sold), 2) AS total_units,
    ROUND(SUM(profit) / SUM(units_sold), 2) AS profit_per_unit,
    ROUND(AVG(discount_pct), 4)              AS avg_discount_pct,
    ROUND(100.0 * SUM(profit) / (SELECT SUM(profit) FROM financials), 2) AS pct_of_total_profit
FROM financials
GROUP BY discount_band
ORDER BY profit_per_unit DESC;
""").fetchdf()
print("\n--- Q04: Discount Band Unit Economics ---")
print(q04)
q04.to_csv("sql_output/q04_discount_band_economics.csv", index=False)


# ------------------------------------------------------------
# 5. CROSS-TAB: COUNTRY × DISCOUNT BAND
# ------------------------------------------------------------
q05 = con.execute("""
SELECT
    country,
    ROUND(SUM(CASE WHEN discount_band = 'None'   THEN profit ELSE 0 END), 2) AS none_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Low'    THEN profit ELSE 0 END), 2) AS low_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Medium' THEN profit ELSE 0 END), 2) AS medium_profit,
    ROUND(SUM(CASE WHEN discount_band = 'High'   THEN profit ELSE 0 END), 2) AS high_profit,
    ROUND(SUM(profit), 2) AS total_profit
FROM financials
GROUP BY country
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q05: Country × Discount Band (Profit) ---")
print(q05)
q05.to_csv("sql_output/q05_country_x_discount.csv", index=False)


# ------------------------------------------------------------
# 6. CROSS-TAB: PRODUCT × DISCOUNT BAND
# ------------------------------------------------------------
q06 = con.execute("""
SELECT
    product,
    ROUND(SUM(CASE WHEN discount_band = 'None'   THEN profit ELSE 0 END), 2) AS none_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Low'    THEN profit ELSE 0 END), 2) AS low_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Medium' THEN profit ELSE 0 END), 2) AS medium_profit,
    ROUND(SUM(CASE WHEN discount_band = 'High'   THEN profit ELSE 0 END), 2) AS high_profit,
    ROUND(SUM(profit), 2) AS total_profit
FROM financials
GROUP BY product
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q06: Product × Discount Band (Profit) ---")
print(q06)
q06.to_csv("sql_output/q06_product_x_discount.csv", index=False)


# ------------------------------------------------------------
# 7. MONTHLY TREND
# ------------------------------------------------------------
q07 = con.execute("""
SELECT
    month_num,
    month_name,
    COUNT(*)                  AS orders,
    ROUND(SUM(sales), 2)      AS sales,
    ROUND(SUM(profit), 2)     AS profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin
FROM financials
GROUP BY month_num, month_name
ORDER BY month_num;
""").fetchdf()
print("\n--- Q07: Monthly Trend ---")
print(q07)
q07.to_csv("sql_output/q07_monthly_trend.csv", index=False)


# ------------------------------------------------------------
# 8. WINDOW FUNCTION — Running YTD Profit by Month
# ------------------------------------------------------------
q08 = con.execute("""
WITH monthly AS (
    SELECT month_num, month_name,
           SUM(profit) AS month_profit
    FROM financials
    GROUP BY month_num, month_name
)
SELECT
    month_num,
    month_name,
    ROUND(month_profit, 2) AS month_profit,
    ROUND(SUM(month_profit) OVER (ORDER BY month_num), 2) AS ytd_profit
FROM monthly
ORDER BY month_num;
""").fetchdf()
print("\n--- Q08: YTD Profit Running Total ---")
print(q08)
q08.to_csv("sql_output/q08_ytd_profit.csv", index=False)


# ------------------------------------------------------------
# 9. WINDOW FUNCTION — Rank Countries Within Each Discount Band
# ------------------------------------------------------------
q09 = con.execute("""
WITH country_band AS (
    SELECT country, discount_band, SUM(profit) AS profit
    FROM financials
    GROUP BY country, discount_band
)
SELECT
    discount_band,
    country,
    ROUND(profit, 2) AS profit,
    RANK() OVER (PARTITION BY discount_band ORDER BY profit DESC) AS rank_in_band
FROM country_band
ORDER BY discount_band, rank_in_band;
""").fetchdf()
print("\n--- Q09: Country Rank Within Each Discount Band ---")
print(q09)
q09.to_csv("sql_output/q09_country_rank_by_band.csv", index=False)


# ------------------------------------------------------------
# 10. CTE — Countries Below Blended Margin
# ------------------------------------------------------------
q10 = con.execute("""
WITH country_margin AS (
    SELECT country,
           SUM(profit) AS profit,
           SUM(sales)  AS sales,
           SUM(profit) / SUM(sales) AS margin
    FROM financials
    GROUP BY country
),
blended AS (
    SELECT SUM(profit) / SUM(sales) AS blended_margin FROM financials
)
SELECT
    c.country,
    ROUND(c.margin, 4) AS margin,
    ROUND(b.blended_margin, 4) AS blended_margin,
    ROUND(c.margin - b.blended_margin, 4) AS gap,
    CASE WHEN c.margin < b.blended_margin THEN 'Below' ELSE 'Above' END AS position
FROM country_margin c, blended b
ORDER BY c.margin DESC;
""").fetchdf()
print("\n--- Q10: Countries vs Blended Margin ---")
print(q10)
q10.to_csv("sql_output/q10_vs_blended_margin.csv", index=False)


# ------------------------------------------------------------
# 11. CASE — Bucket Products by Margin Tier
# ------------------------------------------------------------
q11 = con.execute("""
WITH product_margin AS (
    SELECT product,
           SUM(profit) AS profit,
           SUM(sales)  AS sales,
           SUM(profit) / SUM(sales) AS margin
    FROM financials
    GROUP BY product
)
SELECT
    product,
    ROUND(margin, 4) AS margin,
    CASE
        WHEN margin >= 0.15 THEN 'High Margin'
        WHEN margin >= 0.12 THEN 'Mid Margin'
        ELSE 'Low Margin'
    END AS margin_tier
FROM product_margin
ORDER BY margin DESC;
""").fetchdf()
print("\n--- Q11: Product Margin Tiers ---")
print(q11)
q11.to_csv("sql_output/q11_product_margin_tiers.csv", index=False)


# ------------------------------------------------------------
# 12. JOIN — Product Lookup + Sales Aggregation
# ------------------------------------------------------------
q12 = con.execute("""
WITH product_lookup AS (
    SELECT
        product,
        ROUND(AVG(mfg_price), 2) AS avg_mfg_price,
        ROUND(AVG(sale_price), 2) AS avg_sale_price
    FROM financials
    GROUP BY product
),
product_agg AS (
    SELECT product,
           SUM(units_sold) AS units,
           SUM(sales) AS sales,
           SUM(profit) AS profit
    FROM financials
    GROUP BY product
)
SELECT
    p.product,
    p.avg_mfg_price,
    p.avg_sale_price,
    ROUND(p.avg_sale_price - p.avg_mfg_price, 2) AS gross_spread,
    a.units,
    ROUND(a.sales, 2) AS sales,
    ROUND(a.profit, 2) AS profit,
    ROUND(a.profit / a.sales, 4) AS margin
FROM product_lookup p
JOIN product_agg a USING (product)
ORDER BY a.profit DESC;
""").fetchdf()
print("\n--- Q12: Product Lookup + Sales (JOIN) ---")
print(q12)
q12.to_csv("sql_output/q12_product_join.csv", index=False)


# ------------------------------------------------------------
# 13. SUBQUERY — Top 3 Products by Profit in Each Country
# ------------------------------------------------------------
q13 = con.execute("""
WITH country_product AS (
    SELECT country, product, SUM(profit) AS profit
    FROM financials
    GROUP BY country, product
),
ranked AS (
    SELECT
        country, product, profit,
        ROW_NUMBER() OVER (PARTITION BY country ORDER BY profit DESC) AS rn
    FROM country_product
)
SELECT country, product, ROUND(profit, 2) AS profit
FROM ranked
WHERE rn <= 3
ORDER BY country, profit DESC;
""").fetchdf()
print("\n--- Q13: Top 3 Products by Profit per Country ---")
print(q13)
q13.to_csv("sql_output/q13_top_products_by_country.csv", index=False)


# ------------------------------------------------------------
# 14. CTE + WINDOW — Discount Band Share of Profit per Country
# ------------------------------------------------------------
q14 = con.execute("""
WITH cb AS (
    SELECT country, discount_band, SUM(profit) AS profit
    FROM financials
    GROUP BY country, discount_band
)
SELECT
    country,
    discount_band,
    ROUND(profit, 2) AS profit,
    ROUND(100.0 * profit / SUM(profit) OVER (PARTITION BY country), 2) AS pct_of_country_profit
FROM cb
ORDER BY country, pct_of_country_profit DESC;
""").fetchdf()
print("\n--- Q14: Discount Band Share of Country Profit ---")
print(q14)
q14.to_csv("sql_output/q14_band_share_by_country.csv", index=False)


# ------------------------------------------------------------
# 15. FINAL — Summary View
# ------------------------------------------------------------
q15 = con.execute("""
SELECT
    country,
    product,
    discount_band,
    ROUND(SUM(sales), 2)  AS sales,
    ROUND(SUM(profit), 2) AS profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    CASE
        WHEN SUM(profit) < 0 THEN 'Loss-making'
        WHEN SUM(profit) / SUM(sales) >= 0.15 THEN 'High margin'
        WHEN SUM(profit) / SUM(sales) >= 0.12 THEN 'Mid margin'
        ELSE 'Low margin'
    END AS tier
FROM financials
GROUP BY country, product, discount_band
ORDER BY profit DESC
LIMIT 30;
""").fetchdf()
print("\n--- Q15: Top 30 Country × Product × Discount Combinations ---")
print(q15)
q15.to_csv("sql_output/q15_top_combinations.csv", index=False)


# ------------------------------------------------------------
# ZIP AND DOWNLOAD
# ------------------------------------------------------------
shutil.make_archive("sql_output", "zip", "sql_output")
files.download("sql_output.zip")

print("\n" + "=" * 60)
print("SQL ANALYSIS COMPLETE")
print("=" * 60)
print("Downloaded: sql_output.zip")
print("Contents:")
for f in sorted(os.listdir("sql_output")):
    print("  -", f)

# ============================================================
# FINANCIALS EDA — SENIOR-LEVEL SQL ANALYSIS
# Tool: DuckDB (in-process SQL engine, reads CSV directly)
# ============================================================

!pip install duckdb --quiet

import duckdb
import pandas as pd
import os
import shutil
from google.colab import files

os.makedirs("sql_output", exist_ok=True)
con = duckdb.connect()

# ------------------------------------------------------------
# 0. LOAD AND CLEAN IN SQL
# ------------------------------------------------------------
con.execute("""
CREATE OR REPLACE TABLE financials AS
WITH raw AS (
    SELECT * FROM read_csv_auto('Financials.csv', header=true)
),
cleaned AS (
    SELECT
        TRIM(Segment)   AS segment,
        TRIM(Country)   AS country,
        TRIM(Product)   AS product,
        TRIM("Discount Band") AS discount_band,
        TRIM("Units Sold")      AS units_sold_s,
        TRIM("Manufacturing Price") AS mfg_price_s,
        TRIM("Sale Price")      AS sale_price_s,
        TRIM("Gross Sales")     AS gross_sales_s,
        TRIM(Discounts)         AS discounts_s,
        TRIM(Sales)             AS sales_s,
        TRIM(COGS)              AS cogs_s,
        TRIM(Profit)            AS profit_s,
        "Date"                  AS sale_date,
        "Month Number"          AS month_num,
        TRIM("Month Name")      AS month_name,
        "Year"                  AS year
    FROM raw
    WHERE TRIM(Country) IS NOT NULL
)
SELECT
    segment,
    country,
    product,
    discount_band,
    TRY_CAST(NULLIF(REPLACE(REPLACE(REPLACE(units_sold_s, ',', ''), '$', ''), '-', ''), '') AS DOUBLE) AS units_sold,
    TRY_CAST(NULLIF(REPLACE(REPLACE(REPLACE(mfg_price_s, ',', ''), '$', ''), '-', ''), '') AS DOUBLE) AS mfg_price,
    TRY_CAST(NULLIF(REPLACE(REPLACE(REPLACE(sale_price_s, ',', ''), '$', ''), '-', ''), '') AS DOUBLE) AS sale_price,
    TRY_CAST(NULLIF(REPLACE(REPLACE(REPLACE(gross_sales_s, ',', ''), '$', ''), '-', ''), '') AS DOUBLE) AS gross_sales,
    COALESCE(TRY_CAST(NULLIF(REPLACE(REPLACE(REPLACE(discounts_s, ',', ''), '$', ''), '-', ''), '') AS DOUBLE), 0) AS discounts,
    TRY_CAST(NULLIF(REPLACE(REPLACE(REPLACE(sales_s, ',', ''), '$', ''), '-', ''), '') AS DOUBLE) AS sales,
    TRY_CAST(NULLIF(REPLACE(REPLACE(REPLACE(cogs_s, ',', ''), '$', ''), '-', ''), '') AS DOUBLE) AS cogs,
    TRY_CAST(NULLIF(REPLACE(REPLACE(REPLACE(profit_s, ',', ''), '$', ''), '-', ''), '') AS DOUBLE) AS profit,
    sale_date,
    month_num,
    month_name,
    year
FROM cleaned;
""")

# Add derived columns
con.execute("""
ALTER TABLE financials ADD COLUMN margin DOUBLE;
ALTER TABLE financials ADD COLUMN discount_pct DOUBLE;
""")

con.execute("""
UPDATE financials
SET margin = CASE WHEN sales = 0 OR sales IS NULL THEN NULL ELSE profit / sales END,
    discount_pct = CASE WHEN gross_sales = 0 OR gross_sales IS NULL THEN NULL ELSE discounts / gross_sales END;
""")

print("Table loaded.")
print(con.execute("SELECT COUNT(*) AS rows FROM financials").fetchdf())
print(con.execute("SELECT SUM(sales) AS total_sales, SUM(profit) AS total_profit FROM financials").fetchdf())


# ------------------------------------------------------------
# 1. BASELINE — CORE KPIs
# ------------------------------------------------------------
q01 = con.execute("""
SELECT
    COUNT(*)                          AS orders,
    COUNT(DISTINCT country)           AS countries,
    COUNT(DISTINCT product)           AS products,
    COUNT(DISTINCT segment)           AS segments,
    COUNT(DISTINCT discount_band)     AS discount_bands,
    ROUND(SUM(sales), 2)              AS total_sales,
    ROUND(SUM(cogs), 2)               AS total_cogs,
    ROUND(SUM(profit), 2)             AS total_profit,
    ROUND(SUM(units_sold), 2)         AS total_units,
    ROUND(SUM(profit) / SUM(sales), 4)        AS profit_margin,
    ROUND(SUM(cogs) / SUM(sales), 4)          AS cogs_to_sales,
    ROUND(SUM(profit) / SUM(units_sold), 2)   AS profit_per_unit
FROM financials;
""").fetchdf()
print("\n--- Q01: Core KPIs ---")
print(q01)
q01.to_csv("sql_output/q01_core_kpis.csv", index=False)


# ------------------------------------------------------------
# 2. COUNTRY PERFORMANCE
# ------------------------------------------------------------
q02 = con.execute("""
SELECT
    country,
    ROUND(SUM(sales), 2)      AS total_sales,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(units_sold), 2) AS total_units,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    ROUND(SUM(profit) / SUM(units_sold), 2) AS profit_per_unit
FROM financials
GROUP BY country
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q02: Country Performance ---")
print(q02)
q02.to_csv("sql_output/q02_country_performance.csv", index=False)


# ------------------------------------------------------------
# 3. PRODUCT PERFORMANCE
# ------------------------------------------------------------
q03 = con.execute("""
SELECT
    product,
    ROUND(SUM(sales), 2)      AS total_sales,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    ROUND(100.0 * SUM(profit) / (SELECT SUM(profit) FROM financials), 2) AS pct_of_total_profit
FROM financials
GROUP BY product
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q03: Product Performance (with % of total profit) ---")
print(q03)
q03.to_csv("sql_output/q03_product_performance.csv", index=False)


# ------------------------------------------------------------
# 4. DISCOUNT BAND — UNIT ECONOMICS
# ------------------------------------------------------------
q04 = con.execute("""
SELECT
    discount_band,
    ROUND(SUM(profit), 2)     AS total_profit,
    ROUND(SUM(units_sold), 2) AS total_units,
    ROUND(SUM(profit) / SUM(units_sold), 2) AS profit_per_unit,
    ROUND(AVG(discount_pct), 4)              AS avg_discount_pct,
    ROUND(100.0 * SUM(profit) / (SELECT SUM(profit) FROM financials), 2) AS pct_of_total_profit
FROM financials
GROUP BY discount_band
ORDER BY profit_per_unit DESC;
""").fetchdf()
print("\n--- Q04: Discount Band Unit Economics ---")
print(q04)
q04.to_csv("sql_output/q04_discount_band_economics.csv", index=False)


# ------------------------------------------------------------
# 5. CROSS-TAB: COUNTRY × DISCOUNT BAND
# ------------------------------------------------------------
q05 = con.execute("""
SELECT
    country,
    ROUND(SUM(CASE WHEN discount_band = 'None'   THEN profit ELSE 0 END), 2) AS none_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Low'    THEN profit ELSE 0 END), 2) AS low_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Medium' THEN profit ELSE 0 END), 2) AS medium_profit,
    ROUND(SUM(CASE WHEN discount_band = 'High'   THEN profit ELSE 0 END), 2) AS high_profit,
    ROUND(SUM(profit), 2) AS total_profit
FROM financials
GROUP BY country
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q05: Country × Discount Band (Profit) ---")
print(q05)
q05.to_csv("sql_output/q05_country_x_discount.csv", index=False)


# ------------------------------------------------------------
# 6. CROSS-TAB: PRODUCT × DISCOUNT BAND
# ------------------------------------------------------------
q06 = con.execute("""
SELECT
    product,
    ROUND(SUM(CASE WHEN discount_band = 'None'   THEN profit ELSE 0 END), 2) AS none_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Low'    THEN profit ELSE 0 END), 2) AS low_profit,
    ROUND(SUM(CASE WHEN discount_band = 'Medium' THEN profit ELSE 0 END), 2) AS medium_profit,
    ROUND(SUM(CASE WHEN discount_band = 'High'   THEN profit ELSE 0 END), 2) AS high_profit,
    ROUND(SUM(profit), 2) AS total_profit
FROM financials
GROUP BY product
ORDER BY total_profit DESC;
""").fetchdf()
print("\n--- Q06: Product × Discount Band (Profit) ---")
print(q06)
q06.to_csv("sql_output/q06_product_x_discount.csv", index=False)


# ------------------------------------------------------------
# 7. MONTHLY TREND
# ------------------------------------------------------------
q07 = con.execute("""
SELECT
    month_num,
    month_name,
    COUNT(*)                  AS orders,
    ROUND(SUM(sales), 2)      AS sales,
    ROUND(SUM(profit), 2)     AS profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin
FROM financials
GROUP BY month_num, month_name
ORDER BY month_num;
""").fetchdf()
print("\n--- Q07: Monthly Trend ---")
print(q07)
q07.to_csv("sql_output/q07_monthly_trend.csv", index=False)


# ------------------------------------------------------------
# 8. WINDOW FUNCTION — Running YTD Profit by Month
# ------------------------------------------------------------
q08 = con.execute("""
WITH monthly AS (
    SELECT month_num, month_name,
           SUM(profit) AS month_profit
    FROM financials
    GROUP BY month_num, month_name
)
SELECT
    month_num,
    month_name,
    ROUND(month_profit, 2) AS month_profit,
    ROUND(SUM(month_profit) OVER (ORDER BY month_num), 2) AS ytd_profit
FROM monthly
ORDER BY month_num;
""").fetchdf()
print("\n--- Q08: YTD Profit Running Total ---")
print(q08)
q08.to_csv("sql_output/q08_ytd_profit.csv", index=False)


# ------------------------------------------------------------
# 9. WINDOW FUNCTION — Rank Countries Within Each Discount Band
# ------------------------------------------------------------
q09 = con.execute("""
WITH country_band AS (
    SELECT country, discount_band, SUM(profit) AS profit
    FROM financials
    GROUP BY country, discount_band
)
SELECT
    discount_band,
    country,
    ROUND(profit, 2) AS profit,
    RANK() OVER (PARTITION BY discount_band ORDER BY profit DESC) AS rank_in_band
FROM country_band
ORDER BY discount_band, rank_in_band;
""").fetchdf()
print("\n--- Q09: Country Rank Within Each Discount Band ---")
print(q09)
q09.to_csv("sql_output/q09_country_rank_by_band.csv", index=False)


# ------------------------------------------------------------
# 10. CTE — Countries Below Blended Margin
# ------------------------------------------------------------
q10 = con.execute("""
WITH country_margin AS (
    SELECT country,
           SUM(profit) AS profit,
           SUM(sales)  AS sales,
           SUM(profit) / SUM(sales) AS margin
    FROM financials
    GROUP BY country
),
blended AS (
    SELECT SUM(profit) / SUM(sales) AS blended_margin FROM financials
)
SELECT
    c.country,
    ROUND(c.margin, 4) AS margin,
    ROUND(b.blended_margin, 4) AS blended_margin,
    ROUND(c.margin - b.blended_margin, 4) AS gap,
    CASE WHEN c.margin < b.blended_margin THEN 'Below' ELSE 'Above' END AS position
FROM country_margin c, blended b
ORDER BY c.margin DESC;
""").fetchdf()
print("\n--- Q10: Countries vs Blended Margin ---")
print(q10)
q10.to_csv("sql_output/q10_vs_blended_margin.csv", index=False)


# ------------------------------------------------------------
# 11. CASE — Bucket Products by Margin Tier
# ------------------------------------------------------------
q11 = con.execute("""
WITH product_margin AS (
    SELECT product,
           SUM(profit) AS profit,
           SUM(sales)  AS sales,
           SUM(profit) / SUM(sales) AS margin
    FROM financials
    GROUP BY product
)
SELECT
    product,
    ROUND(margin, 4) AS margin,
    CASE
        WHEN margin >= 0.15 THEN 'High Margin'
        WHEN margin >= 0.12 THEN 'Mid Margin'
        ELSE 'Low Margin'
    END AS margin_tier
FROM product_margin
ORDER BY margin DESC;
""").fetchdf()
print("\n--- Q11: Product Margin Tiers ---")
print(q11)
q11.to_csv("sql_output/q11_product_margin_tiers.csv", index=False)


# ------------------------------------------------------------
# 12. JOIN — Product Lookup + Sales Aggregation
# ------------------------------------------------------------
q12 = con.execute("""
WITH product_lookup AS (
    SELECT
        product,
        ROUND(AVG(mfg_price), 2) AS avg_mfg_price,
        ROUND(AVG(sale_price), 2) AS avg_sale_price
    FROM financials
    GROUP BY product
),
product_agg AS (
    SELECT product,
           SUM(units_sold) AS units,
           SUM(sales) AS sales,
           SUM(profit) AS profit
    FROM financials
    GROUP BY product
)
SELECT
    p.product,
    p.avg_mfg_price,
    p.avg_sale_price,
    ROUND(p.avg_sale_price - p.avg_mfg_price, 2) AS gross_spread,
    a.units,
    ROUND(a.sales, 2) AS sales,
    ROUND(a.profit, 2) AS profit,
    ROUND(a.profit / a.sales, 4) AS margin
FROM product_lookup p
JOIN product_agg a USING (product)
ORDER BY a.profit DESC;
""").fetchdf()
print("\n--- Q12: Product Lookup + Sales (JOIN) ---")
print(q12)
q12.to_csv("sql_output/q12_product_join.csv", index=False)


# ------------------------------------------------------------
# 13. SUBQUERY — Top 3 Products by Profit in Each Country
# ------------------------------------------------------------
q13 = con.execute("""
WITH country_product AS (
    SELECT country, product, SUM(profit) AS profit
    FROM financials
    GROUP BY country, product
),
ranked AS (
    SELECT
        country, product, profit,
        ROW_NUMBER() OVER (PARTITION BY country ORDER BY profit DESC) AS rn
    FROM country_product
)
SELECT country, product, ROUND(profit, 2) AS profit
FROM ranked
WHERE rn <= 3
ORDER BY country, profit DESC;
""").fetchdf()
print("\n--- Q13: Top 3 Products by Profit per Country ---")
print(q13)
q13.to_csv("sql_output/q13_top_products_by_country.csv", index=False)


# ------------------------------------------------------------
# 14. CTE + WINDOW — Discount Band Share of Profit per Country
# ------------------------------------------------------------
q14 = con.execute("""
WITH cb AS (
    SELECT country, discount_band, SUM(profit) AS profit
    FROM financials
    GROUP BY country, discount_band
)
SELECT
    country,
    discount_band,
    ROUND(profit, 2) AS profit,
    ROUND(100.0 * profit / SUM(profit) OVER (PARTITION BY country), 2) AS pct_of_country_profit
FROM cb
ORDER BY country, pct_of_country_profit DESC;
""").fetchdf()
print("\n--- Q14: Discount Band Share of Country Profit ---")
print(q14)
q14.to_csv("sql_output/q14_band_share_by_country.csv", index=False)


# ------------------------------------------------------------
# 15. FINAL — Summary View
# ------------------------------------------------------------
q15 = con.execute("""
SELECT
    country,
    product,
    discount_band,
    ROUND(SUM(sales), 2)  AS sales,
    ROUND(SUM(profit), 2) AS profit,
    ROUND(SUM(profit) / SUM(sales), 4) AS margin,
    CASE
        WHEN SUM(profit) < 0 THEN 'Loss-making'
        WHEN SUM(profit) / SUM(sales) >= 0.15 THEN 'High margin'
        WHEN SUM(profit) / SUM(sales) >= 0.12 THEN 'Mid margin'
        ELSE 'Low margin'
    END AS tier
FROM financials
GROUP BY country, product, discount_band
ORDER BY profit DESC
LIMIT 30;
""").fetchdf()
print("\n--- Q15: Top 30 Country × Product × Discount Combinations ---")
print(q15)
q15.to_csv("sql_output/q15_top_combinations.csv", index=False)


# ------------------------------------------------------------
# ZIP AND DOWNLOAD
# ------------------------------------------------------------
shutil.make_archive("sql_output", "zip", "sql_output")
files.download("sql_output.zip")

print("\n" + "=" * 60)
print("SQL ANALYSIS COMPLETE")
print("=" * 60)
print("Downloaded: sql_output.zip")
print("Contents:")
for f in sorted(os.listdir("sql_output")):
    print("  -", f)