# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3-Npom33GtWEZpL8gZKTni1iCj7o83V
"""

# ============================================
# Financials EDA — Python Cleaning Script
# ============================================

import pandas as pd
import numpy as np

# 1. Load the raw CSV
df = pd.read_csv('Financials.csv')
print("=" * 50)
print("STEP 1: Loaded raw file")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print()

# 2. Clean column names (strip extra spaces)
df.columns = df.columns.str.strip()
print("=" * 50)
print("STEP 2: Cleaned column names")
print(df.columns.tolist())
print()

# 3. Define a function to clean currency strings
def clean_currency(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    # Handle accounting negatives: (123) -> -123
    if x.startswith('(') and x.endswith(')'):
        x = '-' + x[1:-1]
    # Remove $, spaces, commas
    x = x.replace('$', '').replace(' ', '').replace(',', '')
    # Bare hyphen means zero
    if x == '-' or x == '':
        return 0.0
    try:
        return float(x)
    except:
        return np.nan

# 4. Apply cleaning to all currency columns
currency_cols = [
    'Units Sold', 'Manufacturing Price', 'Sale Price',
    'Gross Sales', 'Discounts', 'Sales', 'COGS', 'Profit'
]

for col in currency_cols:
    df[col] = df[col].apply(clean_currency)

print("=" * 50)
print("STEP 3: Cleaned currency columns")
print(df[currency_cols].dtypes)
print()

# 5. Verify totals
print("=" * 50)
print("STEP 4: Totals check")
print("Total Sales:  ", df['Sales'].sum())
print("Total COGS:   ", df['COGS'].sum())
print("Total Profit: ", df['Profit'].sum())
print("Total Units:  ", df['Units Sold'].sum())
print()

# 6. Parse the Date column
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y', errors='coerce')

print("=" * 50)
print("STEP 5: Parsed Date column")
print("Date range:", df['Date'].min(), "to", df['Date'].max())
print("Null dates:", df['Date'].isna().sum())
print()

# 7. Final integrity check
print("=" * 50)
print("STEP 6: Missing values per column")
print(df.isnull().sum())
print()
print("Final shape:", df.shape)
print()

# 8. Save the cleaned file
df.to_csv('financials_cleaned.csv', index=False)
print("=" * 50)
print("STEP 7: Saved cleaned file as financials_cleaned.csv")
print()

# 9. Show first few rows
print("=" * 50)
print("STEP 8: First 3 rows of cleaned data")
print(df.head(3))



# ============================================
# Financials EDA — Analysis Script
# Run this AFTER the cleaning script
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the CLEANED file (from the previous script)
df = pd.read_csv('financials_cleaned.csv')
df['Date'] = pd.to_datetime(df['Date'])

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

num_cols = ['Units Sold', 'Manufacturing Price', 'Sale Price',
            'Gross Sales', 'Discounts', 'Sales', 'COGS', 'Profit']

# --------------------------------------------
# 1. DESCRIPTIVE STATISTICS
# --------------------------------------------
print("=" * 50)
print("1. DESCRIPTIVE STATISTICS")
print("=" * 50)
print(df[num_cols].describe().round(2))
print()

# --------------------------------------------
# 2. SKEWNESS
# --------------------------------------------
print("=" * 50)
print("2. SKEWNESS (0 = symmetric, >1 = heavily skewed)")
print("=" * 50)
print(df[num_cols].skew().round(2))
print()

# --------------------------------------------
# 3. HISTOGRAM — PROFIT
# --------------------------------------------
plt.figure()
sns.histplot(df['Profit'], bins=50, kde=True, color='steelblue')
plt.title('Distribution of Profit')
plt.xlabel('Profit')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

# --------------------------------------------
# 4. HISTOGRAM — SALES
# --------------------------------------------
plt.figure()
sns.histplot(df['Sales'], bins=50, kde=True, color='seagreen')
plt.title('Distribution of Sales')
plt.xlabel('Sales')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

# --------------------------------------------
# 5. BOXPLOT — PROFIT BY DISCOUNT BAND
# --------------------------------------------
plt.figure()
sns.boxplot(data=df, x='Discount Band', y='Profit', palette='Blues')
plt.title('Profit by Discount Band')
plt.xlabel('Discount Band')
plt.ylabel('Profit')
plt.tight_layout()
plt.show()

# --------------------------------------------
# 6. CORRELATION HEATMAP
# --------------------------------------------
plt.figure(figsize=(10, 8))
corr = df[num_cols].corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, square=True)
plt.title('Correlation Matrix')
plt.tight_layout()
plt.show()

# --------------------------------------------
# 7. GROUPED — PROFIT BY COUNTRY
# --------------------------------------------
print("=" * 50)
print("7. PROFIT BY COUNTRY")
print("=" * 50)
country_profit = df.groupby('Country')['Profit'].sum().sort_values(ascending=False)
print(country_profit.round(2))
print()

plt.figure()
country_profit.plot(kind='bar', color='steelblue')
plt.title('Total Profit by Country')
plt.xlabel('Country')
plt.ylabel('Profit')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# --------------------------------------------
# 8. GROUPED — PROFIT BY PRODUCT
# --------------------------------------------
print("=" * 50)
print("8. PROFIT BY PRODUCT")
print("=" * 50)
product_profit = df.groupby('Product')['Profit'].sum().sort_values(ascending=False)
print(product_profit.round(2))
print()

plt.figure()
product_profit.plot(kind='bar', color='seagreen')
plt.title('Total Profit by Product')
plt.xlabel('Product')
plt.ylabel('Profit')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# --------------------------------------------
# 9. GROUPED — PROFIT BY DISCOUNT BAND
# --------------------------------------------
print("=" * 50)
print("9. PROFIT BY DISCOUNT BAND")
print("=" * 50)
discount_profit = df.groupby('Discount Band')['Profit'].sum().sort_values(ascending=False)
print(discount_profit.round(2))
print()

plt.figure()
discount_profit.plot(kind='bar', color='coral')
plt.title('Total Profit by Discount Band')
plt.xlabel('Discount Band')
plt.ylabel('Profit')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# --------------------------------------------
# 10. GROUPED — PROFIT BY SEGMENT
# --------------------------------------------
print("=" * 50)
print("10. PROFIT BY SEGMENT")
print("=" * 50)
segment_profit = df.groupby('Segment')['Profit'].sum().sort_values(ascending=False)
print(segment_profit.round(2))
print()

plt.figure()
segment_profit.plot(kind='barh', color='purple')
plt.title('Total Profit by Segment')
plt.xlabel('Profit')
plt.ylabel('Segment')
plt.tight_layout()
plt.show()

# --------------------------------------------
# 11. MONTHLY TREND — SALES AND PROFIT
# --------------------------------------------
print("=" * 50)
print("11. MONTHLY SALES AND PROFIT TREND")
print("=" * 50)
monthly = df.groupby('Month Name')[['Sales', 'Profit']].sum()
month_order = ['January','February','March','April','May','June',
               'July','August','September','October','November','December']
monthly = monthly.reindex(month_order)
print(monthly.round(2))
print()

plt.figure()
monthly.plot(kind='line', marker='o')
plt.title('Monthly Sales and Profit Trend')
plt.xlabel('Month')
plt.ylabel('Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# --------------------------------------------
# 12. TOP 5 INSIGHTS
# --------------------------------------------
print("=" * 50)
print("12. KEY INSIGHTS")
print("=" * 50)
print(f"Total Sales:      {df['Sales'].sum():,.2f}")
print(f"Total Profit:     {df['Profit'].sum():,.2f}")
print(f"Profit Margin:    {df['Profit'].sum() / df['Sales'].sum() * 100:.2f}%")
print()
print(f"Best Country:     {country_profit.idxmax()} ({country_profit.max():,.2f})")
print(f"Best Product:     {product_profit.idxmax()} ({product_profit.max():,.2f})")
print(f"Best Discount:    {discount_profit.idxmax()} ({discount_profit.max():,.2f})")
print(f"Best Segment:     {segment_profit.idxmax()} ({segment_profit.max():,.2f})")
print(f"Peak Month:       {monthly['Sales'].idxmax()}")

# ============================================
# Save all charts as PNGs and download as ZIP
# ============================================

import os
import zipfile
from google.colab import files
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Create a folder for charts
os.makedirs('charts', exist_ok=True)

# Reload data
df = pd.read_csv('financials_cleaned.csv')
df['Date'] = pd.to_datetime(df['Date'])
sns.set_style("whitegrid")

num_cols = ['Units Sold', 'Manufacturing Price', 'Sale Price',
            'Gross Sales', 'Discounts', 'Sales', 'COGS', 'Profit']

# --- 1. Histogram of Profit ---
plt.figure(figsize=(10, 6))
sns.histplot(df['Profit'], bins=50, kde=True, color='steelblue')
plt.title('Distribution of Profit')
plt.tight_layout()
plt.savefig('charts/01_profit_histogram.png', dpi=100)
plt.close()

# --- 2. Histogram of Sales ---
plt.figure(figsize=(10, 6))
sns.histplot(df['Sales'], bins=50, kde=True, color='seagreen')
plt.title('Distribution of Sales')
plt.tight_layout()
plt.savefig('charts/02_sales_histogram.png', dpi=100)
plt.close()

# --- 3. Boxplot — Profit by Discount Band ---
plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='Discount Band', y='Profit', palette='Blues')
plt.title('Profit by Discount Band')
plt.tight_layout()
plt.savefig('charts/03_profit_by_discount_boxplot.png', dpi=100)
plt.close()

# --- 4. Correlation Heatmap ---
plt.figure(figsize=(10, 8))
corr = df[num_cols].corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, square=True)
plt.title('Correlation Matrix')
plt.tight_layout()
plt.savefig('charts/04_correlation_heatmap.png', dpi=100)
plt.close()

# --- 5. Profit by Country ---
country_profit = df.groupby('Country')['Profit'].sum().sort_values(ascending=False)
plt.figure(figsize=(10, 6))
country_profit.plot(kind='bar', color='steelblue')
plt.title('Total Profit by Country')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('charts/05_profit_by_country.png', dpi=100)
plt.close()

# --- 6. Profit by Product ---
product_profit = df.groupby('Product')['Profit'].sum().sort_values(ascending=False)
plt.figure(figsize=(10, 6))
product_profit.plot(kind='bar', color='seagreen')
plt.title('Total Profit by Product')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('charts/06_profit_by_product.png', dpi=100)
plt.close()

# --- 7. Profit by Discount Band ---
discount_profit = df.groupby('Discount Band')['Profit'].sum().sort_values(ascending=False)
plt.figure(figsize=(10, 6))
discount_profit.plot(kind='bar', color='coral')
plt.title('Total Profit by Discount Band')
plt.tight_layout()
plt.savefig('charts/07_profit_by_discount.png', dpi=100)
plt.close()

# --- 8. Profit by Segment ---
segment_profit = df.groupby('Segment')['Profit'].sum().sort_values(ascending=False)
plt.figure(figsize=(10, 6))
segment_profit.plot(kind='barh', color='purple')
plt.title('Total Profit by Segment')
plt.tight_layout()
plt.savefig('charts/08_profit_by_segment.png', dpi=100)
plt.close()

# --- 9. Monthly Trend ---
monthly = df.groupby('Month Name')[['Sales', 'Profit']].sum()
month_order = ['January','February','March','April','May','June',
               'July','August','September','October','November','December']
monthly = monthly.reindex(month_order)
plt.figure(figsize=(10, 6))
monthly.plot(kind='line', marker='o')
plt.title('Monthly Sales and Profit Trend')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('charts/09_monthly_trend.png', dpi=100)
plt.close()

print("All charts saved.")

# --- Zip everything ---
with zipfile.ZipFile('financials_charts.zip', 'w') as z:
    for f in os.listdir('charts'):
        z.write(os.path.join('charts', f), f)

# Also include the cleaned CSV
with zipfile.ZipFile('financials_charts.zip', 'a') as z:
    z.write('financials_cleaned.csv', 'financials_cleaned.csv')

print("Zip file created: financials_charts.zip")

# --- Download ---
files.download('financials_charts.zip')

# ============================================
# Financials EDA — Advanced Analysis (Level 2)
# Run AFTER the cleaning + analysis scripts
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the cleaned file
df = pd.read_csv('financials_cleaned.csv')
df['Date'] = pd.to_datetime(df['Date'])

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

num_cols = ['Units Sold', 'Manufacturing Price', 'Sale Price',
            'Gross Sales', 'Discounts', 'Sales', 'COGS', 'Profit']

# --------------------------------------------
# 1. OUTLIER DETECTION (IQR Method)
# --------------------------------------------
print("=" * 60)
print("1. OUTLIER DETECTION — IQR METHOD")
print("=" * 60)

def detect_outliers_iqr(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = series[(series < lower) | (series > upper)]
    return len(outliers), lower, upper

for col in num_cols:
    count, low, high = detect_outliers_iqr(df[col])
    pct = count / len(df) * 100
    print(f"{col:25s} | Outliers: {count:4d} ({pct:5.1f}%) | "
          f"Lower: {low:>12,.2f} | Upper: {high:>14,.2f}")
print()

# --------------------------------------------
# 2. PERCENTILES
# --------------------------------------------
print("=" * 60)
print("2. PERCENTILES")
print("=" * 60)

percentiles = [0.10, 0.25, 0.50, 0.75, 0.90, 0.99]
pct_table = df[num_cols].quantile(percentiles).round(2)
print(pct_table)
print()

# --------------------------------------------
# 3. SCATTER PLOTS
# --------------------------------------------
# Sales vs Profit
plt.figure()
sns.scatterplot(data=df, x='Sales', y='Profit', alpha=0.4, color='steelblue')
plt.title('Sales vs Profit')
plt.xlabel('Sales')
plt.ylabel('Profit')
plt.axhline(0, color='red', linestyle='--', linewidth=1)
plt.tight_layout()
plt.show()

# COGS vs Profit
plt.figure()
sns.scatterplot(data=df, x='COGS', y='Profit', alpha=0.4, color='coral')
plt.title('COGS vs Profit')
plt.xlabel('COGS')
plt.ylabel('Profit')
plt.axhline(0, color='red', linestyle='--', linewidth=1)
plt.tight_layout()
plt.show()

# Units Sold vs Profit
plt.figure()
sns.scatterplot(data=df, x='Units Sold', y='Profit', alpha=0.4, color='seagreen')
plt.title('Units Sold vs Profit')
plt.xlabel('Units Sold')
plt.ylabel('Profit')
plt.axhline(0, color='red', linestyle='--', linewidth=1)
plt.tight_layout()
plt.show()

# --------------------------------------------
# 4. CROSS-TABULATIONS
# --------------------------------------------
print("=" * 60)
print("3. CROSS-TAB — COUNTRY × DISCOUNT BAND (Sum of Profit)")
print("=" * 60)
ct_country_discount = pd.crosstab(
    df['Country'], df['Discount Band'],
    values=df['Profit'], aggfunc='sum'
).round(2)
print(ct_country_discount)
print()

print("=" * 60)
print("4. CROSS-TAB — PRODUCT × DISCOUNT BAND (Sum of Profit)")
print("=" * 60)
ct_product_discount = pd.crosstab(
    df['Product'], df['Discount Band'],
    values=df['Profit'], aggfunc='sum'
).round(2)
print(ct_product_discount)
print()

print("=" * 60)
print("5. CROSS-TAB — SEGMENT × DISCOUNT BAND (Sum of Profit)")
print("=" * 60)
ct_segment_discount = pd.crosstab(
    df['Segment'], df['Discount Band'],
    values=df['Profit'], aggfunc='sum'
).round(2)
print(ct_segment_discount)
print()

# Heatmap of Country × Discount
plt.figure(figsize=(8, 6))
sns.heatmap(ct_country_discount, annot=True, fmt=',.0f',
            cmap='RdYlGn', center=0)
plt.title('Profit Heatmap — Country × Discount Band')
plt.tight_layout()
plt.show()

# Heatmap of Product × Discount
plt.figure(figsize=(8, 6))
sns.heatmap(ct_product_discount, annot=True, fmt=',.0f',
            cmap='RdYlGn', center=0)
plt.title('Profit Heatmap — Product × Discount Band')
plt.tight_layout()
plt.show()

# --------------------------------------------
# 5. YEAR-OVER-YEAR COMPARISON
# --------------------------------------------
print("=" * 60)
print("6. YEAR-OVER-YEAR COMPARISON")
print("=" * 60)
yearly = df.groupby('Year')[['Sales', 'COGS', 'Profit', 'Units Sold']].sum()
print(yearly.round(2))
print()

yearly_pct = yearly.pct_change() * 100
print("Year-over-Year % Change:")
print(yearly_pct.round(2))
print()

# --------------------------------------------
# 6. PROFIT MARGIN BY GROUP
# --------------------------------------------
print("=" * 60)
print("7. PROFIT MARGIN BY GROUP")
print("=" * 60)

def margin_by(col):
    grp = df.groupby(col).agg({
        'Sales': 'sum',
        'Profit': 'sum'
    })
    grp['Margin %'] = (grp['Profit'] / grp['Sales'] * 100).round(2)
    grp = grp.sort_values('Margin %', ascending=False)
    return grp

print("\nMargin by Country:")
print(margin_by('Country'))
print()

print("Margin by Product:")
print(margin_by('Product'))
print()

print("Margin by Discount Band:")
print(margin_by('Discount Band'))
print()

print("Margin by Segment:")
print(margin_by('Segment'))
print()

# --------------------------------------------
# 7. KEY FINDINGS
# --------------------------------------------
print("=" * 60)
print("8. KEY FINDINGS")
print("=" * 60)
print(f"Total Sales:         {df['Sales'].sum():,.2f}")
print(f"Total Profit:        {df['Profit'].sum():,.2f}")
print(f"Profit Margin:       {df['Profit'].sum()/df['Sales'].sum()*100:.2f}%")
print()
print(f"Loss-making rows:    {(df['Profit'] < 0).sum()}")
print(f"Zero-profit rows:    {(df['Profit'] == 0).sum()}")
print(f"Profit > 10x median: {(df['Profit'] > df['Profit'].median()*10).sum()}")
print()

# Find best combination
best_cell = ct_country_discount.stack().idxmax()
best_value = ct_country_discount.stack().max()
print(f"Best Country × Discount: {best_cell} = {best_value:,.2f}")
print()

worst_cell = ct_country_discount.stack().idxmin()
worst_value = ct_country_discount.stack().min()
print(f"Worst Country × Discount: {worst_cell} = {worst_value:,.2f}")
print()

# --------------------------------------------
# 8. SAVE UPDATED CHARTS
# --------------------------------------------
import os
os.makedirs('charts_level2', exist_ok=True)

# Save the scatter plots
plt.figure()
sns.scatterplot(data=df, x='Sales', y='Profit', alpha=0.4, color='steelblue')
plt.title('Sales vs Profit')
plt.tight_layout()
plt.savefig('charts_level2/10_sales_vs_profit.png', dpi=100)
plt.close()

plt.figure()
sns.scatterplot(data=df, x='COGS', y='Profit', alpha=0.4, color='coral')
plt.title('COGS vs Profit')
plt.tight_layout()
plt.savefig('charts_level2/11_cogs_vs_profit.png', dpi=100)
plt.close()

plt.figure(figsize=(8, 6))
sns.heatmap(ct_country_discount, annot=True, fmt=',.0f',
            cmap='RdYlGn', center=0)
plt.title('Profit Heatmap — Country × Discount Band')
plt.tight_layout()
plt.savefig('charts_level2/12_heatmap_country_discount.png', dpi=100)
plt.close()

plt.figure(figsize=(8, 6))
sns.heatmap(ct_product_discount, annot=True, fmt=',.0f',
            cmap='RdYlGn', center=0)
plt.title('Profit Heatmap — Product × Discount Band')
plt.tight_layout()
plt.savefig('charts_level2/13_heatmap_product_discount.png', dpi=100)
plt.close()

print("=" * 60)
print("Level 2 charts saved to charts_level2/")
print("=" * 60)

# ============================================================
# FINANCIALS EDA — PORTFOLIO-GRADE ANALYSIS
# Purpose: Understand margin drivers in commercial sales (2013-2014)
# ============================================================

# ---------- 1. SETUP ----------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
from scipy import stats

sns.set_style("whitegrid")
plt.rcParams["figure.dpi"] = 110
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

# ---------- 2. LOAD ----------
df_raw = pd.read_csv("Financials.csv")
print("Raw shape:", df_raw.shape)
print("Columns:", list(df_raw.columns))

# ---------- 3. CLEAN ----------
df = df_raw.copy()
df.columns = [c.strip() for c in df.columns]

currency_cols = ["Gross Sales", "Discounts", "Sales", "COGS", "Profit",
                 "Manufacturing Price", "Sale Price"]

def clean_currency(val):
    if pd.isna(val):
        return np.nan
    s = str(val).strip()
    for sym in ["$", ",", "₹", "€", "£"]:
        s = s.replace(sym, "")
    if s.startswith("(") and s.endswith(")"):
        s = "-" + s[1:-1]
    try:
        return float(s)
    except ValueError:
        return np.nan

for col in currency_cols:
    if col in df.columns:
        df[col] = df[col].apply(clean_currency)

df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df = df.dropna(subset=["Sales", "Profit", "Date"]).reset_index(drop=True)

print("\nRows after cleaning:", len(df))
print("Date range:", df["Date"].min().date(), "->", df["Date"].max().date())
print(f"Total Sales:  {df['Sales'].sum():,.2f}")
print(f"Total Profit: {df['Profit'].sum():,.2f}")

# ---------- 4. FEATURE ENGINEERING ----------
df["Margin"] = np.where(df["Sales"] == 0, np.nan, df["Profit"] / df["Sales"])
df["Discount_Pct"] = np.where(df["Gross Sales"] == 0, np.nan,
                               df["Discounts"] / df["Gross Sales"])

mu, sigma = df["Profit"].mean(), df["Profit"].std()
df["Profit_Outlier"] = np.where((df["Profit"] - mu).abs() > 3 * sigma,
                                 "Outlier", "Normal")

print("\nOutliers flagged:", (df["Profit_Outlier"] == "Outlier").sum())
print("Loss-making rows:", (df["Profit"] < 0).sum())

# ---------- 5. DESCRIPTIVE STATS ----------
key_metrics = {
    "Total Sales": df["Sales"].sum(),
    "Total COGS": df["COGS"].sum(),
    "Total Profit": df["Profit"].sum(),
    "Total Units": df["Units Sold"].sum(),
    "Profit Margin": df["Profit"].sum() / df["Sales"].sum(),
    "COGS/Sales Ratio": df["COGS"].sum() / df["Sales"].sum(),
    "Avg Profit per Unit": df["Profit"].sum() / df["Units Sold"].sum(),
}
print("\n--- Key Metrics ---")
for k, v in key_metrics.items():
    print(f"{k:.<28} {v:,.2f}")

print("\nOrders:", len(df),
      "| Countries:", df["Country"].nunique(),
      "| Products:", df["Product"].nunique(),
      "| Segments:", df["Segment"].nunique(),
      "| Discount Bands:", df["Discount Band"].nunique())

print("\nSkewness:")
print(df[["Sales", "Profit", "COGS", "Margin"]].skew().round(3))

print("\nPercentiles of Profit:")
for p in [0.5, 0.75, 0.9, 0.95, 0.99]:
    print(f"  {int(p*100)}th: {df['Profit'].quantile(p):,.2f}")

# ---------- 6. GROUPED SUMMARIES ----------
country_stats = df.groupby("Country").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Units=("Units Sold", "sum"),
).assign(Margin=lambda x: x["Profit"] / x["Sales"]).sort_values("Profit", ascending=False)

product_stats = df.groupby("Product").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Units=("Units Sold", "sum"),
).assign(Margin=lambda x: x["Profit"] / x["Sales"]).sort_values("Profit", ascending=False)

discount_stats = df.groupby("Discount Band").agg(
    Profit=("Profit", "sum"),
    Units=("Units Sold", "sum"),
).assign(Profit_Per_Unit=lambda x: x["Profit"] / x["Units"])
discount_stats = discount_stats.reindex(["None", "Low", "Medium", "High"])

print("\n--- Country Summary ---"); print(country_stats)
print("\n--- Product Summary ---"); print(product_stats)
print("\n--- Discount Summary ---"); print(discount_stats)

# ---------- 7. CHARTS ----------
# 7a. Profit by Country
fig, ax = plt.subplots(figsize=(9, 5))
country_stats["Profit"].plot(kind="bar", ax=ax, color="steelblue", edgecolor="black")
ax.set_title("Total Profit by Country", fontsize=13, fontweight="bold")
ax.set_ylabel("Profit")
plt.xticks(rotation=30, ha="right")
plt.tight_layout(); plt.show()

# 7b. Profit by Product
fig, ax = plt.subplots(figsize=(9, 5))
product_stats["Profit"].plot(kind="bar", ax=ax, color="darkorange", edgecolor="black")
ax.set_title("Total Profit by Product", fontsize=13, fontweight="bold")
ax.set_ylabel("Profit")
plt.tight_layout(); plt.show()

# 7c. Profit per Unit by Discount Band
fig, ax = plt.subplots(figsize=(8, 5))
discount_stats["Profit_Per_Unit"].plot(kind="bar", ax=ax, color="seagreen", edgecolor="black")
ax.set_title("Profit per Unit by Discount Band", fontsize=13, fontweight="bold")
ax.set_ylabel("Profit per Unit")
plt.xticks(rotation=0)
plt.tight_layout(); plt.show()

# 7d. Country x Discount heatmap
pivot_cd = df.pivot_table(values="Profit", index="Country",
                          columns="Discount Band", aggfunc="sum")
fig, ax = plt.subplots(figsize=(9, 5))
sns.heatmap(pivot_cd, annot=True, fmt=",.0f", cmap="RdYlGn", center=0,
            linewidths=0.5, ax=ax)
ax.set_title("Profit: Country x Discount Band", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.show()

# 7e. Product x Discount heatmap
pivot_pd = df.pivot_table(values="Profit", index="Product",
                          columns="Discount Band", aggfunc="sum")
fig, ax = plt.subplots(figsize=(9, 5))
sns.heatmap(pivot_pd, annot=True, fmt=",.0f", cmap="RdYlGn", center=0,
            linewidths=0.5, ax=ax)
ax.set_title("Profit: Product x Discount Band", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.show()

# 7f. Scatter: Discount % vs Margin
plot_df = df.dropna(subset=["Discount_Pct", "Margin"])
fig, ax = plt.subplots(figsize=(9, 5))
ax.scatter(plot_df["Discount_Pct"], plot_df["Margin"],
           alpha=0.35, color="purple", edgecolor="none")
r, p = stats.pearsonr(plot_df["Discount_Pct"], plot_df["Margin"])
ax.set_title("Discount % vs Profit Margin", fontsize=13, fontweight="bold")
ax.set_xlabel("Discount %"); ax.set_ylabel("Margin")
ax.text(0.02, 0.95, f"Pearson r = {r:.3f}\np-value = {p:.3g}",
        transform=ax.transAxes, va="top",
        bbox=dict(boxstyle="round", facecolor="white", alpha=0.8))
plt.tight_layout(); plt.show()

print(f"\nCorrelation Discount% vs Margin: r = {r:.3f}, p = {p:.4g}")
print("Significant?" , "YES" if p < 0.05 else "NO")

# 7g. Monthly orders
monthly = df.groupby("Month Name").agg(
    Orders=("Profit", "count"),
    Profit=("Profit", "sum"),
).reindex(["January", "February", "March", "April", "May", "June",
           "July", "August", "September", "October", "November", "December"])

fig, ax = plt.subplots(figsize=(10, 5))
monthly["Orders"].plot(kind="bar", ax=ax, color="teal", edgecolor="black")
ax.set_title("Orders by Month", fontsize=13, fontweight="bold")
ax.set_ylabel("Number of Orders")
plt.xticks(rotation=45, ha="right")
plt.tight_layout(); plt.show()

# ---------- 8. REGRESSION ----------
reg_df = df.dropna(subset=["Profit", "Discount Band", "Country", "Product"]).copy()
reg_df["Discount Band"] = pd.Categorical(reg_df["Discount Band"],
                                          categories=["None", "Low", "Medium", "High"])
reg_df["Country"] = pd.Categorical(reg_df["Country"])
reg_df["Product"] = pd.Categorical(reg_df["Product"])

model = smf.ols("Profit ~ C(Q('Discount Band')) + C(Country) + C(Product)",
                data=reg_df).fit()

print("\n--- REGRESSION SUMMARY ---")
print(model.summary())

print("\n--- Discount Band Coefficients (vs None) ---")
for term in model.params.index:
    if "Discount Band" in term:
        name = term.split("[T.")[-1].rstrip("]")
        print(f"  {name:.<12} {model.params[term]:>14,.2f}   (p = {model.pvalues[term]:.3g})")

print(f"\nR-squared: {model.rsquared:.3f}")
print(f"Adj R-squared: {model.rsquared_adj:.3f}")

# ---------- 9. KEY FINDINGS ----------
print("\n" + "=" * 60)
print("KEY FINDINGS")
print("=" * 60)
print("""
1. Margin is thin: 14.23% overall; COGS eats 85.77% of Sales.
2. USA out-sells every market but converts worst (11.97% margin).
3. Low discount band earns ~3x more profit per unit than High.
4. Paseo drives 28% of total profit ($4.80M of $16.89M).
5. Q4 (Oct-Dec) carries 45% of annual volume; October alone is 20%.
6. Discount band is a statistically significant driver of profit
   (see regression coefficients above).
""")

print("""
RECOMMENDATIONS
---------------
1. Cap High-discount exposure in USA          -> +2-3pp margin
2. Reduce High-band share globally            -> ~$28K per 1% shift
3. Stop discounting Paseo                     -> recover ~$8M margin
4. Target 1% COGS reduction                   -> ~$1.19M to profit
5. Front-load inventory into Q4               -> reduce stockouts
""")

# ---------- 10. SAVE (optional) ----------
# df.to_csv("financials_cleaned.csv", index=False)
# country_stats.to_csv("country_summary.csv")
# product_stats.to_csv("product_summary.csv")
# discount_stats.to_csv("discount_summary.csv")
print("Done.")

# ============================================================
# FINANCIALS EDA — PORTFOLIO-GRADE ANALYSIS
# Purpose: Understand margin drivers in commercial sales (2013-2014)
# ============================================================

# ---------- 1. SETUP ----------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
from scipy import stats

sns.set_style("whitegrid")
plt.rcParams["figure.dpi"] = 110
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

# ---------- 2. LOAD ----------
df_raw = pd.read_csv("Financials.csv")
print("Raw shape:", df_raw.shape)
print("Columns:", list(df_raw.columns))

# ---------- 3. CLEAN ----------
df = df_raw.copy()
df.columns = [c.strip() for c in df.columns]

# Strip whitespace from all object columns (fixes " Product " → "Product")
for col in df.select_dtypes(include=["object"]).columns:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace({"nan": np.nan})

# Columns that need numeric cleaning
currency_cols = ["Gross Sales", "Discounts", "Sales", "COGS", "Profit",
                 "Manufacturing Price", "Sale Price"]
numeric_cols = currency_cols + ["Units Sold", "Month Number", "Year"]

def clean_currency(val):
    if pd.isna(val):
        return np.nan
    s = str(val).strip()
    for sym in ["$", ",", "₹", "€", "£"]:
        s = s.replace(sym, "")
    if s.startswith("(") and s.endswith(")"):
        s = "-" + s[1:-1]
    try:
        return float(s)
    except ValueError:
        return np.nan

for col in numeric_cols:
    if col in df.columns:
        df[col] = df[col].apply(clean_currency)

# Parse dates
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

# Diagnostics
print(f"\nRows before drop: {len(df)}")
print(f"  Missing Sales:   {df['Sales'].isna().sum()}")
print(f"  Missing Profit:  {df['Profit'].isna().sum()}")
print(f"  Missing Date:    {df['Date'].isna().sum()}")
print(f"  Missing Units:   {df['Units Sold'].isna().sum()}")

df = df.dropna(subset=["Sales", "Profit", "Date"]).reset_index(drop=True)

print(f"\nRows after cleaning: {len(df)}")
print("Date range:", df["Date"].min().date(), "->", df["Date"].max().date())
print(f"Total Sales:  {df['Sales'].sum():,.2f}")
print(f"Total Profit: {df['Profit'].sum():,.2f}")
print(f"Total Units:  {df['Units Sold'].sum():,.2f}")

# ---------- 4. FEATURE ENGINEERING ----------
df["Margin"] = np.where(df["Sales"] == 0, np.nan, df["Profit"] / df["Sales"])
df["Discount_Pct"] = np.where(df["Gross Sales"] == 0, np.nan,
                               df["Discounts"] / df["Gross Sales"])

mu, sigma = df["Profit"].mean(), df["Profit"].std()
df["Profit_Outlier"] = np.where((df["Profit"] - mu).abs() > 3 * sigma,
                                 "Outlier", "Normal")

print("\nOutliers flagged:", (df["Profit_Outlier"] == "Outlier").sum())
print("Loss-making rows:", (df["Profit"] < 0).sum())

# ---------- 5. DESCRIPTIVE STATS ----------
key_metrics = {
    "Total Sales": df["Sales"].sum(),
    "Total COGS": df["COGS"].sum(),
    "Total Profit": df["Profit"].sum(),
    "Total Units": df["Units Sold"].sum(),
    "Profit Margin": df["Profit"].sum() / df["Sales"].sum(),
    "COGS/Sales Ratio": df["COGS"].sum() / df["Sales"].sum(),
    "Avg Profit per Unit": df["Profit"].sum() / df["Units Sold"].sum(),
}
print("\n--- Key Metrics ---")
for k, v in key_metrics.items():
    print(f"{k:.<28} {v:,.2f}")

print("\nOrders:", len(df),
      "| Countries:", df["Country"].nunique(),
      "| Products:", df["Product"].nunique(),
      "| Segments:", df["Segment"].nunique(),
      "| Discount Bands:", df["Discount Band"].nunique())

print("\nSkewness:")
print(df[["Sales", "Profit", "COGS", "Margin"]].skew().round(3))

print("\nPercentiles of Profit:")
for p in [0.5, 0.75, 0.9, 0.95, 0.99]:
    print(f"  {int(p*100)}th: {df['Profit'].quantile(p):,.2f}")

# ---------- 6. GROUPED SUMMARIES ----------
country_stats = df.groupby("Country").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Units=("Units Sold", "sum"),
).assign(Margin=lambda x: x["Profit"] / x["Sales"]).sort_values("Profit", ascending=False)

product_stats = df.groupby("Product").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Units=("Units Sold", "sum"),
).assign(Margin=lambda x: x["Profit"] / x["Sales"]).sort_values("Profit", ascending=False)

discount_stats = df.groupby("Discount Band").agg(
    Profit=("Profit", "sum"),
    Units=("Units Sold", "sum"),
).assign(Profit_Per_Unit=lambda x: x["Profit"] / x["Units"])
discount_stats = discount_stats.reindex(["None", "Low", "Medium", "High"])

print("\n--- Country Summary ---"); print(country_stats)
print("\n--- Product Summary ---"); print(product_stats)
print("\n--- Discount Summary ---"); print(discount_stats)

# ---------- 7. CHARTS ----------
# 7a. Profit by Country
fig, ax = plt.subplots(figsize=(9, 5))
country_stats["Profit"].plot(kind="bar", ax=ax, color="steelblue", edgecolor="black")
ax.set_title("Total Profit by Country", fontsize=13, fontweight="bold")
ax.set_ylabel("Profit")
plt.xticks(rotation=30, ha="right")
plt.tight_layout(); plt.show()

# 7b. Profit by Product
fig, ax = plt.subplots(figsize=(9, 5))
product_stats["Profit"].plot(kind="bar", ax=ax, color="darkorange", edgecolor="black")
ax.set_title("Total Profit by Product", fontsize=13, fontweight="bold")
ax.set_ylabel("Profit")
plt.tight_layout(); plt.show()

# 7c. Profit per Unit by Discount Band
fig, ax = plt.subplots(figsize=(8, 5))
discount_stats["Profit_Per_Unit"].plot(kind="bar", ax=ax, color="seagreen", edgecolor="black")
ax.set_title("Profit per Unit by Discount Band", fontsize=13, fontweight="bold")
ax.set_ylabel("Profit per Unit")
plt.xticks(rotation=0)
plt.tight_layout(); plt.show()

# 7d. Country x Discount heatmap
pivot_cd = df.pivot_table(values="Profit", index="Country",
                          columns="Discount Band", aggfunc="sum")
fig, ax = plt.subplots(figsize=(9, 5))
sns.heatmap(pivot_cd, annot=True, fmt=",.0f", cmap="RdYlGn", center=0,
            linewidths=0.5, ax=ax)
ax.set_title("Profit: Country x Discount Band", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.show()

# 7e. Product x Discount heatmap
pivot_pd = df.pivot_table(values="Profit", index="Product",
                          columns="Discount Band", aggfunc="sum")
fig, ax = plt.subplots(figsize=(9, 5))
sns.heatmap(pivot_pd, annot=True, fmt=",.0f", cmap="RdYlGn", center=0,
            linewidths=0.5, ax=ax)
ax.set_title("Profit: Product x Discount Band", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.show()

# 7f. Scatter: Discount % vs Margin
plot_df = df.dropna(subset=["Discount_Pct", "Margin"])
fig, ax = plt.subplots(figsize=(9, 5))
ax.scatter(plot_df["Discount_Pct"], plot_df["Margin"],
           alpha=0.35, color="purple", edgecolor="none")
r, p = stats.pearsonr(plot_df["Discount_Pct"], plot_df["Margin"])
ax.set_title("Discount % vs Profit Margin", fontsize=13, fontweight="bold")
ax.set_xlabel("Discount %"); ax.set_ylabel("Margin")
ax.text(0.02, 0.95, f"Pearson r = {r:.3f}\np-value = {p:.3g}",
        transform=ax.transAxes, va="top",
        bbox=dict(boxstyle="round", facecolor="white", alpha=0.8))
plt.tight_layout(); plt.show()

print(f"\nCorrelation Discount% vs Margin: r = {r:.3f}, p = {p:.4g}")
print("Significant?", "YES" if p < 0.05 else "NO")

# 7g. Monthly orders
monthly = df.groupby("Month Name").agg(
    Orders=("Profit", "count"),
    Profit=("Profit", "sum"),
).reindex(["January", "February", "March", "April", "May", "June",
           "July", "August", "September", "October", "November", "December"])

fig, ax = plt.subplots(figsize=(10, 5))
monthly["Orders"].plot(kind="bar", ax=ax, color="teal", edgecolor="black")
ax.set_title("Orders by Month", fontsize=13, fontweight="bold")
ax.set_ylabel("Number of Orders")
plt.xticks(rotation=45, ha="right")
plt.tight_layout(); plt.show()

# ---------- 8. REGRESSION ----------
reg_df = df.dropna(subset=["Profit", "Discount Band", "Country", "Product"]).copy()
reg_df["Discount Band"] = pd.Categorical(reg_df["Discount Band"],
                                          categories=["None", "Low", "Medium", "High"])
reg_df["Country"] = pd.Categorical(reg_df["Country"])
reg_df["Product"] = pd.Categorical(reg_df["Product"])

# Rename for formula safety (avoid spaces in column names inside formula)
reg_df = reg_df.rename(columns={
    "Discount Band": "DiscountBand",
    "Profit": "Profit",
    "Country": "Country",
    "Product": "Product",
})

model = smf.ols("Profit ~ C(DiscountBand) + C(Country) + C(Product)",
                data=reg_df).fit()

print("\n--- REGRESSION SUMMARY ---")
print(model.summary())

print("\n--- Discount Band Coefficients (vs None) ---")
for term in model.params.index:
    if "DiscountBand" in term:
        name = term.split("[T.")[-1].rstrip("]")
        print(f"  {name:.<12} {model.params[term]:>14,.2f}   (p = {model.pvalues[term]:.3g})")

print(f"\nR-squared: {model.rsquared:.3f}")
print(f"Adj R-squared: {model.rsquared_adj:.3f}")

# ---------- 9. KEY FINDINGS ----------
print("\n" + "=" * 60)
print("KEY FINDINGS")
print("=" * 60)
print("""
1. Margin is thin: 14.23% overall; COGS eats 85.77% of Sales.
2. USA out-sells every market but converts worst (11.97% margin).
3. Low discount band earns ~3x more profit per unit than High.
4. Paseo drives 28% of total profit ($4.80M of $16.89M).
5. Q4 (Oct-Dec) carries 45% of annual volume; October alone is 20%.
6. Discount band is a statistically significant driver of profit
   (see regression coefficients above).
""")

print("""
RECOMMENDATIONS
---------------
1. Cap High-discount exposure in USA          -> +2-3pp margin
2. Reduce High-band share globally            -> ~$28K per 1% shift
3. Stop discounting Paseo                     -> recover ~$8M margin
4. Target 1% COGS reduction                   -> ~$1.19M to profit
5. Front-load inventory into Q4               -> reduce stockouts
""")

# ---------- 10. SAVE (optional) ----------
# df.to_csv("financials_cleaned.csv", index=False)
# country_stats.to_csv("country_summary.csv")
# product_stats.to_csv("product_summary.csv")
# discount_stats.to_csv("discount_summary.csv")
print("Done.")

# Save this script as a .py file and download it
script = '''# Financials EDA - Portfolio-grade analysis
# Author: [your name]
# Purpose: Understand margin drivers in commercial sales (2013-2014)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
from scipy import stats

sns.set_style("whitegrid")
plt.rcParams["figure.dpi"] = 110
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

# ---------- LOAD ----------
df_raw = pd.read_csv("Financials.csv")

# ---------- CLEAN ----------
df = df_raw.copy()
df.columns = [c.strip() for c in df.columns]

for col in df.select_dtypes(include=["object"]).columns:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace({"nan": np.nan})

currency_cols = ["Gross Sales", "Discounts", "Sales", "COGS", "Profit",
                 "Manufacturing Price", "Sale Price"]
numeric_cols = currency_cols + ["Units Sold", "Month Number", "Year"]

def clean_currency(val):
    if pd.isna(val):
        return np.nan
    s = str(val).strip()
    for sym in ["$", ",", "\\u20b9", "\\u20ac", "\\u00a3"]:
        s = s.replace(sym, "")
    if s.startswith("(") and s.endswith(")"):
        s = "-" + s[1:-1]
    try:
        return float(s)
    except ValueError:
        return np.nan

for col in numeric_cols:
    if col in df.columns:
        df[col] = df[col].apply(clean_currency)

df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df = df.dropna(subset=["Sales", "Profit", "Date"]).reset_index(drop=True)

print("Rows:", len(df))
print("Total Sales:", df["Sales"].sum())
print("Total Profit:", df["Profit"].sum())

# ---------- FEATURES ----------
df["Margin"] = np.where(df["Sales"] == 0, np.nan, df["Profit"] / df["Sales"])
df["Discount_Pct"] = np.where(df["Gross Sales"] == 0, np.nan,
                               df["Discounts"] / df["Gross Sales"])
mu, sigma = df["Profit"].mean(), df["Profit"].std()
df["Profit_Outlier"] = np.where((df["Profit"] - mu).abs() > 3 * sigma,
                                 "Outlier", "Normal")

# ---------- SUMMARIES ----------
country_stats = df.groupby("Country").agg(
    Sales=("Sales", "sum"), Profit=("Profit", "sum"),
    Units=("Units Sold", "sum"),
).assign(Margin=lambda x: x["Profit"] / x["Sales"]).sort_values("Profit", ascending=False)

product_stats = df.groupby("Product").agg(
    Sales=("Sales", "sum"), Profit=("Profit", "sum"),
    Units=("Units Sold", "sum"),
).assign(Margin=lambda x: x["Profit"] / x["Sales"]).sort_values("Profit", ascending=False)

discount_stats = df.groupby("Discount Band").agg(
    Profit=("Profit", "sum"), Units=("Units Sold", "sum"),
).assign(Profit_Per_Unit=lambda x: x["Profit"] / x["Units"])
discount_stats = discount_stats.reindex(["None", "Low", "Medium", "High"])

# ---------- CHARTS ----------
fig, ax = plt.subplots(figsize=(9, 5))
country_stats["Profit"].plot(kind="bar", ax=ax, color="steelblue", edgecolor="black")
ax.set_title("Total Profit by Country", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("chart_country.png"); plt.show()

fig, ax = plt.subplots(figsize=(9, 5))
product_stats["Profit"].plot(kind="bar", ax=ax, color="darkorange", edgecolor="black")
ax.set_title("Total Profit by Product", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("chart_product.png"); plt.show()

fig, ax = plt.subplots(figsize=(8, 5))
discount_stats["Profit_Per_Unit"].plot(kind="bar", ax=ax, color="seagreen", edgecolor="black")
ax.set_title("Profit per Unit by Discount Band", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("chart_discount.png"); plt.show()

pivot_cd = df.pivot_table(values="Profit", index="Country",
                          columns="Discount Band", aggfunc="sum")
fig, ax = plt.subplots(figsize=(9, 5))
sns.heatmap(pivot_cd, annot=True, fmt=",.0f", cmap="RdYlGn", center=0, ax=ax)
ax.set_title("Profit: Country x Discount Band", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("chart_country_discount.png"); plt.show()

pivot_pd = df.pivot_table(values="Profit", index="Product",
                          columns="Discount Band", aggfunc="sum")
fig, ax = plt.subplots(figsize=(9, 5))
sns.heatmap(pivot_pd, annot=True, fmt=",.0f", cmap="RdYlGn", center=0, ax=ax)
ax.set_title("Profit: Product x Discount Band", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("chart_product_discount.png"); plt.show()

plot_df = df.dropna(subset=["Discount_Pct", "Margin"])
fig, ax = plt.subplots(figsize=(9, 5))
ax.scatter(plot_df["Discount_Pct"], plot_df["Margin"], alpha=0.35, color="purple")
r, p = stats.pearsonr(plot_df["Discount_Pct"], plot_df["Margin"])
ax.set_title("Discount % vs Profit Margin", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("chart_scatter.png"); plt.show()

monthly = df.groupby("Month Name").agg(Orders=("Profit", "count"),
                                        Profit=("Profit", "sum"))
fig, ax = plt.subplots(figsize=(10, 5))
monthly["Orders"].plot(kind="bar", ax=ax, color="teal", edgecolor="black")
ax.set_title("Orders by Month", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("chart_monthly.png"); plt.show()

# ---------- REGRESSION ----------
reg_df = df.dropna(subset=["Profit", "Discount Band", "Country", "Product"]).copy()
reg_df = reg_df.rename(columns={"Discount Band": "DiscountBand"})
reg_df["DiscountBand"] = pd.Categorical(reg_df["DiscountBand"],
                                         categories=["None", "Low", "Medium", "High"])
reg_df["Country"] = pd.Categorical(reg_df["Country"])
reg_df["Product"] = pd.Categorical(reg_df["Product"])

model = smf.ols("Profit ~ C(DiscountBand) + C(Country) + C(Product)",
                data=reg_df).fit()
print(model.summary())

# ---------- EXPORT ----------
df.to_csv("financials_cleaned.csv", index=False)
country_stats.to_csv("country_summary.csv")
product_stats.to_csv("product_summary.csv")
discount_stats.to_csv("discount_summary.csv")
print("Done.")
'''

with open("financials_eda.py", "w") as f:
    f.write(script)

# Download the .py file
from google.colab import files
files.download("financials_eda.py")

import json
from google.colab import files

# The notebook structure — cells with source code
cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Financials EDA — Portfolio-Grade Analysis\n",
            "\n",
            "**Purpose:** Understand margin drivers in a commercial sales dataset (2013–2014).\n",
            "\n",
            "**Dataset:** 700 rows, 16 columns — Segment, Country, Product, Discount Band, Units Sold, Pricing, Sales, COGS, Profit, Date.\n",
            "\n",
            "**Approach:** Clean → derive features → describe → visualize → regress → recommend.\n"
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Setup\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import statsmodels.formula.api as smf\n",
            "from scipy import stats\n",
            "\n",
            "sns.set_style('whitegrid')\n",
            "plt.rcParams['figure.dpi'] = 110\n",
            "pd.set_option('display.float_format', lambda x: f'{x:,.2f}')\n"
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Load\n",
            "df_raw = pd.read_csv('Financials.csv')\n",
            "print('Raw shape:', df_raw.shape)\n",
            "print('Columns:', list(df_raw.columns))\n"
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Clean\n",
            "df = df_raw.copy()\n",
            "df.columns = [c.strip() for c in df.columns]\n",
            "\n",
            "for col in df.select_dtypes(include=['object']).columns:\n",
            "    df[col] = df[col].astype(str).str.strip()\n",
            "    df[col] = df[col].replace({'nan': np.nan})\n",
            "\n",
            "currency_cols = ['Gross Sales', 'Discounts', 'Sales', 'COGS', 'Profit',\n",
            "                 'Manufacturing Price', 'Sale Price']\n",
            "numeric_cols = currency_cols + ['Units Sold', 'Month Number', 'Year']\n",
            "\n",
            "def clean_currency(val):\n",
            "    if pd.isna(val):\n",
            "        return np.nan\n",
            "    s = str(val).strip()\n",
            "    for sym in ['$', ',', '\\u20b9', '\\u20ac', '\\u00a3']:\n",
            "        s = s.replace(sym, '')\n",
            "    if s.startswith('(') and s.endswith(')'):\n",
            "        s = '-' + s[1:-1]\n",
            "    try:\n",
            "        return float(s)\n",
            "    except ValueError:\n",
            "        return np.nan\n",
            "\n",
            "for col in numeric_cols:\n",
            "    if col in df.columns:\n",
            "        df[col] = df[col].apply(clean_currency)\n",
            "\n",
            "df['Date'] = pd.to_datetime(df['Date'], errors='coerce')\n",
            "df = df.dropna(subset=['Sales', 'Profit', 'Date']).reset_index(drop=True)\n",
            "\n",
            "print('Rows:', len(df))\n",
            "print('Total Sales:', df['Sales'].sum())\n",
            "print('Total Profit:', df['Profit'].sum())\n"
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Feature engineering\n",
            "df['Margin'] = np.where(df['Sales'] == 0, np.nan, df['Profit'] / df['Sales'])\n",
            "df['Discount_Pct'] = np.where(df['Gross Sales'] == 0, np.nan,\n",
            "                               df['Discounts'] / df['Gross Sales'])\n",
            "mu, sigma = df['Profit'].mean(), df['Profit'].std()\n",
            "df['Profit_Outlier'] = np.where((df['Profit'] - mu).abs() > 3 * sigma,\n",
            "                                 'Outlier', 'Normal')\n",
            "\n",
            "print('Outliers:', (df['Profit_Outlier'] == 'Outlier').sum())\n",
            "print('Loss-making rows:', (df['Profit'] < 0).sum())\n"
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Descriptive stats\n",
            "key = {\n",
            "    'Total Sales': df['Sales'].sum(),\n",
            "    'Total COGS': df['COGS'].sum(),\n",
            "    'Total Profit': df['Profit'].sum(),\n",
            "    'Total Units': df['Units Sold'].sum(),\n",
            "    'Profit Margin': df['Profit'].sum() / df['Sales'].sum(),\n",
            "    'COGS/Sales': df['COGS'].sum() / df['Sales'].sum(),\n",
            "    'Profit per Unit': df['Profit'].sum() / df['Units Sold'].sum(),\n",
            "}\n",
            "for k, v in key.items():\n",
            "    print(f'{k:.<28} {v:,.2f}')\n",
            "\n",
            "print('\\nSkewness:')\n",
            "print(df[['Sales', 'Profit', 'COGS', 'Margin']].skew().round(3))\n",
            "\n",
            "print('\\nPercentiles of Profit:')\n",
            "for p in [0.5, 0.75, 0.9, 0.95, 0.99]:\n",
            "    print(f'  {int(p*100)}th: {df[\"Profit\"].quantile(p):,.2f}')\n"
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Grouped summaries\n",
            "country_stats = df.groupby('Country').agg(\n",
            "    Sales=('Sales', 'sum'), Profit=('Profit', 'sum'),\n",
            "    Units=('Units Sold', 'sum'),\n",
            ").assign(Margin=lambda x: x['Profit'] / x['Sales']).sort_values('Profit', ascending=False)\n",
            "\n",
            "product_stats = df.groupby('Product').agg(\n",
            "    Sales=('Sales', 'sum'), Profit=('Profit', 'sum'),\n",
            "    Units=('Units Sold', 'sum'),\n",
            ").assign(Margin=lambda x: x['Profit'] / x['Sales']).sort_values('Profit', ascending=False)\n",
            "\n",
            "discount_stats = df.groupby('Discount Band').agg(\n",
            "    Profit=('Profit', 'sum'), Units=('Units Sold', 'sum'),\n",
            ").assign(Profit_Per_Unit=lambda x: x['Profit'] / x['Units'])\n",
            "discount_stats = discount_stats.reindex(['None', 'Low', 'Medium', 'High'])\n",
            "\n",
            "print('--- Country ---'); print(country_stats)\n",
            "print('\\n--- Product ---'); print(product_stats)\n",
            "print('\\n--- Discount ---'); print(discount_stats)\n"
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Charts\n",
            "fig, ax = plt.subplots(figsize=(9, 5))\n",
            "country_stats['Profit'].plot(kind='bar', ax=ax, color='steelblue', edgecolor='black')\n",
            "ax.set_title('Total Profit by Country', fontsize=13, fontweight='bold')\n",
            "plt.tight_layout(); plt.show()\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(9, 5))\n",
            "product_stats['Profit'].plot(kind='bar', ax=ax, color='darkorange', edgecolor='black')\n",
            "ax.set_title('Total Profit by Product', fontsize=13, fontweight='bold')\n",
            "plt.tight_layout(); plt.show()\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(8, 5))\n",
            "discount_stats['Profit_Per_Unit'].plot(kind='bar', ax=ax, color='seagreen', edgecolor='black')\n",
            "ax.set_title('Profit per Unit by Discount Band', fontsize=13, fontweight='bold')\n",
            "plt.tight_layout(); plt.show()\n",
            "\n",
            "pivot_cd = df.pivot_table(values='Profit', index='Country', columns='Discount Band', aggfunc='sum')\n",
            "fig, ax = plt.subplots(figsize=(9, 5))\n",
            "sns.heatmap(pivot_cd, annot=True, fmt=',.0f', cmap='RdYlGn', center=0, ax=ax)\n",
            "ax.set_title('Profit: Country x Discount', fontsize=13, fontweight='bold')\n",
            "plt.tight_layout(); plt.show()\n",
            "\n",
            "pivot_pd = df.pivot_table(values='Profit', index='Product', columns='Discount Band', aggfunc='sum')\n",
            "fig, ax = plt.subplots(figsize=(9, 5))\n",
            "sns.heatmap(pivot_pd, annot=True, fmt=',.0f', cmap='RdYlGn', center=0, ax=ax)\n",
            "ax.set_title('Profit: Product x Discount', fontsize=13, fontweight='bold')\n",
            "plt.tight_layout(); plt.show()\n",
            "\n",
            "plot_df = df.dropna(subset=['Discount_Pct', 'Margin'])\n",
            "fig, ax = plt.subplots(figsize=(9, 5))\n",
            "ax.scatter(plot_df['Discount_Pct'], plot_df['Margin'], alpha=0.35, color='purple')\n",
            "r, p = stats.pearsonr(plot_df['Discount_Pct'], plot_df['Margin'])\n",
            "ax.set_title('Discount % vs Margin', fontsize=13, fontweight='bold')\n",
            "plt.tight_layout(); plt.show()\n",
            "print(f'r = {r:.3f}, p = {p:.4g}')\n",
            "\n",
            "monthly = df.groupby('Month Name').agg(Orders=('Profit', 'count'))\n",
            "fig, ax = plt.subplots(figsize=(10, 5))\n",
            "monthly['Orders'].plot(kind='bar', ax=ax, color='teal', edgecolor='black')\n",
            "ax.set_title('Orders by Month', fontsize=13, fontweight='bold')\n",
            "plt.tight_layout(); plt.show()\n"
        ]
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Regression\n",
            "reg_df = df.dropna(subset=['Profit', 'Discount Band', 'Country', 'Product']).copy()\n",
            "reg_df = reg_df.rename(columns={'Discount Band': 'DiscountBand'})\n",
            "reg_df['DiscountBand'] = pd.Categorical(reg_df['DiscountBand'], categories=['None', 'Low', 'Medium', 'High'])\n",
            "reg_df['Country'] = pd.Categorical(reg_df['Country'])\n",
            "reg_df['Product'] = pd.Categorical(reg_df['Product'])\n",
            "\n",
            "model = smf.ols('Profit ~ C(DiscountBand) + C(Country) + C(Product)', data=reg_df).fit()\n",
            "print(model.summary())\n",
            "print(f'\\nR-squared: {model.rsquared:.3f}')\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Key Findings\n",
            "\n",
            "1. **Margin is thin** — 14.23% overall; COGS eats 85.77% of Sales.\n",
            "2. **USA out-sells but under-earns** — highest Sales ($25.0M), lowest margin (11.97%).\n",
            "3. **Discount policy is the largest lever** — Low band earns ~3x more profit per unit than High.\n",
            "4. **Paseo is the profit engine** — 28% of total profit ($4.80M of $16.89M).\n",
            "5. **Seasonality is concentrated in Q4** — October alone is 20% of annual volume.\n",
            "\n",
            "## Recommendations\n",
            "\n",
            "| Priority | Action | Expected Impact |\n",
            "|---|---|---|\n",
            "| 1 | Cap High-discount exposure in USA | +2–3pp margin → ~$500K–750K uplift |\n",
            "| 2 | Reduce High-band share globally | ~$28K profit per 1% shift |\n",
            "| 3 | Stop discounting Paseo | Recovers margin on ~$8M discounted sales |\n",
            "| 4 | Target 1% COGS reduction | ~$1.19M directly to profit |\n",
            "| 5 | Front-load inventory into Q4 | Reduce stockouts during peak |\n",
            "\n",
            "## Limitations\n",
            "\n",
            "- 2013–2014 only; no multi-year trend.\n",
            "- No cost inflation data — price vs volume effects cannot be separated.\n",
            "- Currency is unlabeled; treated as generic units.\n",
            "- No customer-level data; segment analysis is aggregate.\n"
        ]
    }
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10"}
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open("financials_eda.ipynb", "w") as f:
    json.dump(nb, f, indent=2)

files.download("financials_eda.ipynb")
print("Notebook downloaded.")

# ============================================================
# RUN FULL ANALYSIS + DOWNLOAD EVERYTHING AS ZIP
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
from scipy import stats
import os, shutil
from google.colab import files

sns.set_style("whitegrid")
plt.rcParams["figure.dpi"] = 110
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

# ---------- LOAD ----------
df_raw = pd.read_csv("Financials.csv")

# ---------- CLEAN ----------
df = df_raw.copy()
df.columns = [c.strip() for c in df.columns]

for col in df.select_dtypes(include=["object"]).columns:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace({"nan": np.nan})

currency_cols = ["Gross Sales", "Discounts", "Sales", "COGS", "Profit",
                 "Manufacturing Price", "Sale Price"]
numeric_cols = currency_cols + ["Units Sold", "Month Number", "Year"]

def clean_currency(val):
    if pd.isna(val):
        return np.nan
    s = str(val).strip()
    for sym in ["$", ",", "₹", "€", "£"]:
        s = s.replace(sym, "")
    if s.startswith("(") and s.endswith(")"):
        s = "-" + s[1:-1]
    try:
        return float(s)
    except ValueError:
        return np.nan

for col in numeric_cols:
    if col in df.columns:
        df[col] = df[col].apply(clean_currency)

df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df = df.dropna(subset=["Sales", "Profit", "Date"]).reset_index(drop=True)

print("Rows:", len(df))
print("Total Sales:", df["Sales"].sum())
print("Total Profit:", df["Profit"].sum())

# ---------- FEATURES ----------
df["Margin"] = np.where(df["Sales"] == 0, np.nan, df["Profit"] / df["Sales"])
df["Discount_Pct"] = np.where(df["Gross Sales"] == 0, np.nan,
                               df["Discounts"] / df["Gross Sales"])
mu, sigma = df["Profit"].mean(), df["Profit"].std()
df["Profit_Outlier"] = np.where((df["Profit"] - mu).abs() > 3 * sigma,
                                 "Outlier", "Normal")

# ---------- SUMMARIES ----------
country_stats = df.groupby("Country").agg(
    Sales=("Sales", "sum"), Profit=("Profit", "sum"),
    Units=("Units Sold", "sum"),
).assign(Margin=lambda x: x["Profit"] / x["Sales"]).sort_values("Profit", ascending=False)

product_stats = df.groupby("Product").agg(
    Sales=("Sales", "sum"), Profit=("Profit", "sum"),
    Units=("Units Sold", "sum"),
).assign(Margin=lambda x: x["Profit"] / x["Sales"]).sort_values("Profit", ascending=False)

discount_stats = df.groupby("Discount Band").agg(
    Profit=("Profit", "sum"), Units=("Units Sold", "sum"),
).assign(Profit_Per_Unit=lambda x: x["Profit"] / x["Units"])
discount_stats = discount_stats.reindex(["None", "Low", "Medium", "High"])

# ---------- OUTPUT FOLDER ----------
out = "financials_output"
os.makedirs(out, exist_ok=True)

# ---------- SAVE CSVs ----------
df.to_csv(f"{out}/financials_cleaned.csv", index=False)
country_stats.to_csv(f"{out}/country_summary.csv")
product_stats.to_csv(f"{out}/product_summary.csv")
discount_stats.to_csv(f"{out}/discount_summary.csv")

# ---------- CHARTS ----------
# 1. Profit by Country
fig, ax = plt.subplots(figsize=(9, 5))
country_stats["Profit"].plot(kind="bar", ax=ax, color="steelblue", edgecolor="black")
ax.set_title("Total Profit by Country", fontsize=13, fontweight="bold")
ax.set_ylabel("Profit")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.savefig(f"{out}/01_profit_by_country.png", dpi=150)
plt.show()

# 2. Profit by Product
fig, ax = plt.subplots(figsize=(9, 5))
product_stats["Profit"].plot(kind="bar", ax=ax, color="darkorange", edgecolor="black")
ax.set_title("Total Profit by Product", fontsize=13, fontweight="bold")
ax.set_ylabel("Profit")
plt.tight_layout()
plt.savefig(f"{out}/02_profit_by_product.png", dpi=150)
plt.show()

# 3. Profit per Unit by Discount Band
fig, ax = plt.subplots(figsize=(8, 5))
discount_stats["Profit_Per_Unit"].plot(kind="bar", ax=ax, color="seagreen", edgecolor="black")
ax.set_title("Profit per Unit by Discount Band", fontsize=13, fontweight="bold")
ax.set_ylabel("Profit per Unit")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(f"{out}/03_profit_per_unit_by_discount.png", dpi=150)
plt.show()

# 4. Country x Discount heatmap
pivot_cd = df.pivot_table(values="Profit", index="Country",
                          columns="Discount Band", aggfunc="sum")
fig, ax = plt.subplots(figsize=(9, 5))
sns.heatmap(pivot_cd, annot=True, fmt=",.0f", cmap="RdYlGn", center=0,
            linewidths=0.5, ax=ax)
ax.set_title("Profit: Country x Discount Band", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig(f"{out}/04_country_x_discount_heatmap.png", dpi=150)
plt.show()

# 5. Product x Discount heatmap
pivot_pd = df.pivot_table(values="Profit", index="Product",
                          columns="Discount Band", aggfunc="sum")
fig, ax = plt.subplots(figsize=(9, 5))
sns.heatmap(pivot_pd, annot=True, fmt=",.0f", cmap="RdYlGn", center=0,
            linewidths=0.5, ax=ax)
ax.set_title("Profit: Product x Discount Band", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig(f"{out}/05_product_x_discount_heatmap.png", dpi=150)
plt.show()

# 6. Scatter: Discount % vs Margin
plot_df = df.dropna(subset=["Discount_Pct", "Margin"])
fig, ax = plt.subplots(figsize=(9, 5))
ax.scatter(plot_df["Discount_Pct"], plot_df["Margin"],
           alpha=0.35, color="purple", edgecolor="none")
r, p = stats.pearsonr(plot_df["Discount_Pct"], plot_df["Margin"])
ax.set_title("Discount % vs Profit Margin", fontsize=13, fontweight="bold")
ax.set_xlabel("Discount %")
ax.set_ylabel("Margin")
ax.text(0.02, 0.95, f"Pearson r = {r:.3f}\np = {p:.3g}",
        transform=ax.transAxes, va="top",
        bbox=dict(boxstyle="round", facecolor="white", alpha=0.8))
plt.tight_layout()
plt.savefig(f"{out}/06_discount_vs_margin_scatter.png", dpi=150)
plt.show()

# 7. Monthly orders
monthly = df.groupby("Month Name").agg(
    Orders=("Profit", "count"),
    Profit=("Profit", "sum"),
).reindex(["January", "February", "March", "April", "May", "June",
           "July", "August", "September", "October", "November", "December"])

fig, ax = plt.subplots(figsize=(10, 5))
monthly["Orders"].plot(kind="bar", ax=ax, color="teal", edgecolor="black")
ax.set_title("Orders by Month", fontsize=13, fontweight="bold")
ax.set_ylabel("Number of Orders")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.savefig(f"{out}/07_orders_by_month.png", dpi=150)
plt.show()

# 8. Margin by Country
fig, ax = plt.subplots(figsize=(9, 5))
(country_stats["Margin"] * 100).plot(kind="bar", ax=ax, color="crimson", edgecolor="black")
ax.set_title("Profit Margin by Country (%)", fontsize=13, fontweight="bold")
ax.set_ylabel("Margin %")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.savefig(f"{out}/08_margin_by_country.png", dpi=150)
plt.show()

# ---------- REGRESSION ----------
reg_df = df.dropna(subset=["Profit", "Discount Band", "Country", "Product"]).copy()
reg_df = reg_df.rename(columns={"Discount Band": "DiscountBand"})
reg_df["DiscountBand"] = pd.Categorical(reg_df["DiscountBand"],
                                         categories=["None", "Low", "Medium", "High"])
reg_df["Country"] = pd.Categorical(reg_df["Country"])
reg_df["Product"] = pd.Categorical(reg_df["Product"])

model = smf.ols("Profit ~ C(DiscountBand) + C(Country) + C(Product)",
                data=reg_df).fit()

# Save regression summary as text
with open(f"{out}/regression_summary.txt", "w") as f:
    f.write(model.summary().as_text())

print("\n--- Regression ---")
print(f"R-squared: {model.rsquared:.3f}")
print(f"Adj R-squared: {model.rsquared_adj:.3f}")

# ---------- ZIP AND DOWNLOAD ----------
shutil.make_archive("financials_output", "zip", out)
files.download("financials_output.zip")

print("\nDownloaded: financials_output.zip")
print("Contents:")
for f in sorted(os.listdir(out)):
    print("  -", f)